#!/usr/bin/env python
"""Grade src/hume_core/eta.h against mordred over the 20,000-molecule dedupe2 corpus.

TEST HARNESS ONLY.  No descriptor value is computed here: Python parses the SMILES, marshals
src/hume/_extract.py's boundary arrays into a flat file, runs the C++ that eta.h compiles into,
and compares the result against mordred's own numbers.  The arithmetic lives in eta.h.

    .venv/bin/python verify_eta.py            # full corpus, all 29 columns
    .venv/bin/python verify_eta.py --limit N  # first N molecules

GROUND TRUTH IS RECOMPUTED IN float64, NOT READ OUT OF matrix.npz.  `data/dedupe2/matrix.npz`
stores mordred's values as float32, so "bit-identical" against it would mean agreeing to 7
digits and no more -- a bar this header clears with room to spare and which would hide the last
eight digits of every eta sum.  This script therefore shells out to `.venv-mordred/bin/python`
once and caches the float64 answers in build_eta/mordred_eta.npz.  It still cross-checks the
float32 matrix afterwards, so a disagreement about WHICH molecules are NaN cannot hide either.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build_eta"
COLS = [
    "ETA_alpha", "ETA_shape_p", "ETA_shape_y", "ETA_shape_x",
    "ETA_beta", "ETA_beta_s", "ETA_beta_ns", "ETA_beta_ns_d",
    "ETA_eta", "ETA_eta_L", "ETA_eta_R", "ETA_eta_F", "ETA_eta_FL", "ETA_eta_B", "ETA_eta_BR",
    "ETA_dAlpha_A", "ETA_dAlpha_B",
    "ETA_epsilon_1", "ETA_epsilon_2", "ETA_epsilon_3", "ETA_epsilon_4", "ETA_epsilon_5",
    "ETA_dEpsilon_A", "ETA_dEpsilon_B", "ETA_dEpsilon_C", "ETA_dEpsilon_D",
    "ETA_dBeta", "ETA_psi_1", "ETA_dPsi_B",
]
NC = len(COLS)

# --------------------------------------------------------------------------------------------
# the C++ driver.  eta.h is a header with no main(), exactly like autocorr.h; cpp/ac.cpp is the
# standalone that wraps that one.  This agent may not add files under cpp/, so the equivalent
# driver is emitted into the build directory and compiled there.
# --------------------------------------------------------------------------------------------
DRIVER = r"""
// Generated by verify_eta.py.  Reads the boundary arrays src/hume/_extract.py produced, calls
// eta::compute once per molecule and writes the 29 values plus a per-molecule timing.
//
// THE TIMER IS CPU TIME AND THE BEST OF THREE PASSES, not wall clock on one pass.  Up to five
// agents build and run in this checkout at once; on a loaded machine the same molecule measured
// 161,386 us of wall clock and 120 us of work.  `CLOCK_THREAD_CPUTIME_ID` does not count the
// time this thread spent descheduled, and every input is read into memory before the timed loop
// starts so no I/O is inside it.
#include "eta.h"

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <string>
#include <vector>

static void rd(std::FILE *f, void *p, std::size_t n) {
  if (std::fread(p, 1, n, f) != n) { std::fprintf(stderr, "short read\n"); std::exit(2); }
}

static double cpu_us() {
  struct timespec ts;
  clock_gettime(CLOCK_THREAD_CPUTIME_ID, &ts);
  return (double)ts.tv_sec * 1e6 + (double)ts.tv_nsec / 1e3;
}

struct Input {
  int n = 0, nb = 0, nring = 0;
  std::vector<std::int32_t> ai, bi;
  std::vector<double> bd;
};

int main(int argc, char **argv) {
  if (argc != 4) { std::fprintf(stderr, "usage: drv in.bin out.bin err.txt\n"); return 2; }
  std::FILE *in = std::fopen(argv[1], "rb");
  if (!in) { std::perror(argv[1]); return 2; }
  std::int32_t nmol = 0;
  rd(in, &nmol, 4);

  std::vector<Input> mols((std::size_t)nmol);
  for (int k = 0; k < nmol; ++k) {
    std::int32_t hdr[3];
    rd(in, hdr, 12);
    Input &q = mols[(std::size_t)k];
    q.n = hdr[0]; q.nb = hdr[1]; q.nring = hdr[2];
    q.ai.resize((std::size_t)q.n * 13);
    q.bi.resize((std::size_t)q.nb * 6);
    q.bd.resize((std::size_t)q.nb);
    if (q.n) rd(in, q.ai.data(), (std::size_t)q.n * 13 * 4);
    if (q.nb) rd(in, q.bi.data(), (std::size_t)q.nb * 6 * 4);
    if (q.nb) rd(in, q.bd.data(), (std::size_t)q.nb * 8);
  }
  std::fclose(in);

  std::vector<double> outv((std::size_t)nmol * eta::N_COLS, 0.0);
  std::vector<double> tus((std::size_t)nmol, 1e300);
  std::string errs;

  eta::Mol m;
  eta::Work W;
  for (int pass = 0; pass < 3; ++pass) {
    for (int k = 0; k < nmol; ++k) {
      const Input &q = mols[(std::size_t)k];
      double *o = &outv[(std::size_t)k * eta::N_COLS];
      const double t0 = cpu_us();
      try {
        eta::build_from_rows(m, q.n, q.nb, q.ai.data(), 13, q.bi.data(), 6, q.bd.data(), q.nring);
        eta::compute(m, o, W);
      } catch (const std::exception &e) {
        if (pass == 0) { errs += std::to_string(k); errs += "\t"; errs += e.what(); errs += "\n"; }
        for (int c = 0; c < eta::N_COLS; ++c) o[c] = std::nan("");
      }
      const double dt = cpu_us() - t0;
      if (dt < tus[(std::size_t)k]) tus[(std::size_t)k] = dt;
    }
  }

  std::FILE *out = std::fopen(argv[2], "wb");
  if (!out) { std::perror(argv[2]); return 2; }
  std::fwrite(outv.data(), 8, outv.size(), out);
  std::fwrite(tus.data(), 8, tus.size(), out);
  std::fclose(out);

  std::FILE *ef = std::fopen(argv[3], "w");
  std::fwrite(errs.data(), 1, errs.size(), ef);
  std::fclose(ef);
  return 0;
}
"""

MORDRED_SCRIPT = r"""
import json, sys
import numpy as np
from rdkit import Chem, RDLogger
RDLogger.DisableLog("rdApp.*")
from mordred import Calculator
from mordred import ExtendedTopochemicalAtom as E


def main():
    WANT = json.loads(sys.argv[3])
    descs = [d for name in E.__all__ for d in getattr(E, name).preset(None)]
    keep = [d for d in descs if str(d) in set(WANT)]
    calc = Calculator(keep, ignore_3D=True)
    names = [str(d) for d in calc.descriptors]

    smis = json.load(open(sys.argv[1]))["smiles"]
    if len(sys.argv) > 4:
        smis = smis[: int(sys.argv[4])]
    mols = [Chem.MolFromSmiles(s) for s in smis]
    ok = [m for m in mols if m is not None]
    rows = [[v if isinstance(v, (int, float)) else np.nan for v in r.values()]
            for r in calc.map(ok, nproc=8, quiet=True)]
    V = np.full((len(mols), len(names)), np.nan, np.float64)
    V[[i for i, m in enumerate(mols) if m is not None]] = np.asarray(rows, dtype=np.float64)
    idx = [names.index(w) for w in WANT]
    np.savez(sys.argv[2], V=V[:, idx], names=np.array(WANT, dtype=object))


if __name__ == "__main__":
    main()
"""


def build_driver() -> Path:
    BUILD.mkdir(exist_ok=True)
    src = BUILD / "eta_driver.cpp"
    src.write_text(DRIVER)
    exe = BUILD / "eta_driver"
    cmd = ["c++", "-O3", "-std=c++17", "-I", str(ROOT / "src" / "hume_core"),
           str(src), "-o", str(exe)]
    print("  $ " + " ".join(cmd))
    subprocess.run(cmd, check=True)
    return exe


def write_input(mols, path: Path) -> Path:
    """Boundary arrays -> one flat file, through src/hume/_extract.py itself."""
    # The INSTALLED hume._extract, which is byte-identical to src/hume/_extract.py; importing it
    # from the source tree would half-initialise the package and shadow the built extension.
    from hume import _extract

    with open(path, "wb") as fh:
        fh.write(np.int32(len(mols)).tobytes())
        for lo in range(0, len(mols), 2000):
            chunk = mols[lo:lo + 2000]
            b = _extract.extract(chunk, stereo=False)
            r = b.rings
            for q in range(len(chunk)):
                a0, a1 = int(b.atom_off[q]), int(b.atom_off[q + 1])
                b0, b1 = int(b.bond_off[q]), int(b.bond_off[q + 1])
                nring = int(r.ring_moff[q + 1] - r.ring_moff[q])
                fh.write(np.array([a1 - a0, b1 - b0, nring], np.int32).tobytes())
                fh.write(np.ascontiguousarray(b.atom_i[a0:a1], np.int32).tobytes())
                fh.write(np.ascontiguousarray(b.bond_i[b0:b1], np.int32).tobytes())
                fh.write(np.ascontiguousarray(b.bond_d[b0:b1], np.float64).tobytes())
    return path


def run_driver(exe: Path, mols, tag: str):
    inp = write_input(mols, BUILD / f"eta_in_{tag}.bin")
    outp, errp = BUILD / f"eta_out_{tag}.bin", BUILD / f"eta_err_{tag}.txt"
    t0 = time.time()
    subprocess.run([str(exe), str(inp), str(outp), str(errp)], check=True)
    raw = np.fromfile(outp, np.float64)
    nm = len(mols)
    return raw[: nm * NC].reshape(nm, NC), raw[nm * NC:], errp.read_text().strip(), time.time() - t0


def marshal(smis) -> tuple[list, list]:
    from rdkit import Chem, RDLogger

    RDLogger.DisableLog("rdApp.*")
    mols = [Chem.MolFromSmiles(s) for s in smis]
    good = [i for i, m in enumerate(mols) if m is not None]
    if len(good) != len(mols):
        print(f"  {len(mols) - len(good)} SMILES failed to parse and are skipped")
    return [mols[i] for i in good], good


def mordred_truth(limit: int | None) -> tuple[np.ndarray, list[str]]:
    cache = BUILD / ("mordred_eta%s.npz" % ("" if limit is None else f"_{limit}"))
    if cache.exists():
        z = np.load(cache, allow_pickle=True)
        return z["V"], [str(x) for x in z["names"]]
    script = BUILD / "mordred_eta.py"
    script.write_text(MORDRED_SCRIPT)
    args = [str(ROOT / ".venv-mordred" / "bin" / "python"), str(script),
            str(ROOT / "data" / "dedupe2" / "corpus.json"), str(cache), json.dumps(COLS)]
    if limit is not None:
        args.append(str(limit))
    print("  $ " + " ".join(args[:4]) + " ...")
    t0 = time.time()
    subprocess.run(args, check=True)
    print(f"  mordred float64 ground truth: {time.time() - t0:.0f}s")
    z = np.load(cache, allow_pickle=True)
    return z["V"], [str(x) for x in z["names"]]


def invariance(exe: Path, smis, ntrial: int = 3, sample: int = 4000) -> None:
    """Is each of the 29 a function of the MOLECULE, or of how it was written down?

    Contract rule 4 turns on this distinction, and the ETA block has two axes that could move a
    value without the molecule changing: the atom numbering, and which Kekule structure the
    perceiver picked.  Both are screened here on a stratified sample:

      renumber       Chem.RenumberAtoms with a random permutation, `ntrial` times each.  Bonds
                     keep their original order with the endpoints rewritten, which is a weaker
                     shuffle than it looks -- so the second axis matters.
      kekule         Chem.Kekulize(clearAromaticFlags=True), written to SMILES and re-parsed.
                     Atom order, bond order AND the Kekule assignment all change at once.  This
                     is the axis that moves mordred's own ETA_epsilon_4, and the one this header
                     is deliberately blind to: the saturated skeleton is rebuilt from the graph,
                     so a different input Kekule structure cannot reach it.
    """
    import random

    from rdkit import Chem, RDLogger

    RDLogger.DisableLog("rdApp.*")
    random.seed(20240823)
    step = max(1, len(smis) // sample)
    pick = smis[::step][:sample]
    base_mols = [m for m in (Chem.MolFromSmiles(s) for s in pick) if m is not None]
    base, _, _, _ = run_driver(exe, base_mols, "inv0")

    variants = {"renumber": [], "kekule": []}
    for m in base_mols:
        idx = list(range(m.GetNumAtoms()))
        for _ in range(ntrial):
            random.shuffle(idx)
            variants["renumber"].append(Chem.RenumberAtoms(m, idx))
        k = Chem.Mol(m)
        try:
            Chem.Kekulize(k, clearAromaticFlags=True)
            q = Chem.MolFromSmiles(Chem.MolToSmiles(k, kekuleSmiles=True))
        except Exception:
            q = None
        variants["kekule"].append(q if q is not None else Chem.Mol(m))

    print(f"\nINVARIANCE SCREEN  ({len(base_mols)} molecules, {ntrial} renumberings each)")
    print("  A cell is REAL movement only past 1e-9 relative AND 1e-12 absolute.  Below that it")
    print("  is summation order -- a reordered sum of non-dyadic doubles has a different last")
    print("  bit -- or the cancellation in `max(alpha - alpha_R, 0)`, where a 1e-16 residual can")
    print("  flip sign and read as an infinite RELATIVE change of a number that is zero.")
    print("  %-16s %9s %9s %11s %9s %9s %11s" %
          ("column", "renum!=", "renum mv", "renum |d|", "kek!=", "kek mv", "kek |d|"))
    stat = {}
    for axis, ms in variants.items():
        V, _, _, _ = run_driver(exe, ms, "inv_" + axis)
        reps = ntrial if axis == "renumber" else 1
        V = V.reshape(len(base_mols), reps, NC)
        bitdiff = np.zeros(NC, np.int64)
        realdiff = np.zeros(NC, np.int64)
        maxabs = np.zeros(NC)
        for r in range(reps):
            a, b = V[:, r, :], base
            both_nan = np.isnan(a) & np.isnan(b)
            bitdiff += ((a != b) & ~both_nan).sum(axis=0)
            fin = np.isfinite(a) & np.isfinite(b)
            ad = np.zeros_like(a)
            rel = np.zeros_like(a)
            ad[fin] = np.abs(a[fin] - b[fin])
            rel[fin] = ad[fin] / np.maximum(np.abs(b[fin]), 1e-300)
            bad = ~fin & ~both_nan          # one side missing, the other not: always real
            ad[bad] = np.inf
            realdiff += (((rel > 1e-9) & (ad > 1e-12)) | bad).sum(axis=0)
            maxabs = np.maximum(maxabs, ad.max(axis=0))
        stat[axis] = (bitdiff, realdiff, maxabs)
    for c, name in enumerate(COLS):
        rn, kk = stat["renumber"], stat["kekule"]
        print("  %-16s %9d %9d %11.2e %9d %9d %11.2e" %
              (name, rn[0][c], rn[1][c], rn[2][c], kk[0][c], kk[1][c], kk[2][c]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--invariance", action="store_true",
                    help="also run the renumbering / Kekule screen")
    args = ap.parse_args()

    BUILD.mkdir(exist_ok=True)
    corpus = json.load(open(ROOT / "data" / "dedupe2" / "corpus.json"))
    smis = corpus["smiles"]
    strat = corpus["stratum"]
    if args.limit:
        smis, strat = smis[:args.limit], strat[:args.limit]
    print(f"{len(smis):,} molecules")

    print("compiling the driver")
    exe = build_driver()

    print("marshalling the boundary arrays")
    mols, parsed = marshal(smis)
    ours_p, tus, errtxt, wall = run_driver(exe, mols, "main")
    nm = len(parsed)

    OURS = np.full((len(smis), NC), np.nan)
    OURS[parsed] = ours_p

    print("mordred ground truth (float64)")
    REF, names = mordred_truth(args.limit)
    REF = REF[: len(smis)]
    assert names == COLS, "mordred column order moved"

    if errtxt:
        print("\nC++ EXCEPTIONS")
        for line in errtxt.splitlines()[:20]:
            k, msg = line.split("\t", 1)
            print(f"  {smis[parsed[int(k)]]}\n    {msg}")
        print(f"  ({len(errtxt.splitlines())} molecules threw)")

    # ----------------------------------------------------------------------------------------
    print("\n%-16s %7s %7s %7s %7s %7s %9s" %
          ("column", "exact", "<1e-9", "<1e-6", "bad", "nanOK", "nanDIFF"))
    print("-" * 72)
    worst = []
    total_bad = 0
    for c, name in enumerate(COLS):
        a, b = OURS[:, c], REF[:, c]
        na, nb = np.isnan(a), np.isnan(b)
        nan_ok = int((na & nb).sum())
        nan_diff = int((na ^ nb).sum())
        both = ~na & ~nb
        d = np.abs(a[both] - b[both])
        scale = np.maximum(np.abs(b[both]), 1e-300)
        rel = d / scale
        exact = int((a[both] == b[both]).sum())
        w9 = int((rel < 1e-9).sum())
        w6 = int((rel < 1e-6).sum())
        bad = int((rel >= 1e-6).sum()) + nan_diff
        total_bad += bad
        print("%-16s %7d %7d %7d %7d %7d %9d" % (name, exact, w9, w6, bad, nan_ok, nan_diff))
        if bad:
            idx = np.where(both)[0][rel >= 1e-6]
            idx = np.concatenate([idx, np.where(na ^ nb)[0]])
            for i in idx[:6]:
                worst.append((name, smis[int(i)], b[int(i)], a[int(i)]))
    print("-" * 72)
    print(f"total cells outside 1e-6 relative (NaN disagreements included): {total_bad}")

    if worst:
        print("\nMISMATCHES (column, SMILES, mordred, ours)")
        for name, s, ref, ours in worst[:60]:
            print(f"  {name:16s} {s}\n      mordred={ref!r}  ours={ours!r}")

    # ---- cross-check against the stored float32 matrix, purely as a NaN-set audit ------------
    mz = np.load(ROOT / "data" / "dedupe2" / "matrix.npz", allow_pickle=True)
    md = [str(x) for x in mz["md_names"]]
    MD = mz["MD"][: len(smis)]
    mism = 0
    for c, name in enumerate(COLS):
        col = MD[:, md.index(name)]
        mism += int((np.isnan(col) ^ np.isnan(OURS[:, c])).sum())
    print(f"\nNaN-set disagreements against the stored float32 matrix.npz: {mism}")

    # ---- timing ------------------------------------------------------------------------------
    print("\nTIMING  (eta::build_from_rows + eta::compute, us/molecule)")
    st = np.asarray(strat, dtype=object)
    stp = st[parsed]
    print("  %-12s %7s %9s %9s" % ("stratum", "n", "mean", "sd"))
    for s in ["0-15", "15-25", "25-35", "35-55", "55-1000000"]:
        sel = stp == s
        if not sel.any():
            continue
        print("  %-12s %7d %9.2f %9.2f" % (s, int(sel.sum()), tus[sel].mean(), tus[sel].std()))
    print("  %-12s %7d %9.2f %9.2f" % ("ALL", len(tus), tus.mean(), tus.std()))
    print(f"  wall clock for {nm:,} molecules including process start: {wall:.2f}s")
    print("  HUME's whole-molecule budget is ~830 us; this group adds "
          f"{tus.mean():.2f} us ({100 * tus.mean() / 830:.2f}%).")

    if args.invariance:
        invariance(exe, smis)
    return 0 if total_bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
