#!/usr/bin/env python
"""Verification harness for src/hume_core/spectral.h -- the 65 B_spectral columns.

    .venv/bin/python verify_spectral.py             # build, run, grade, time
    .venv/bin/python verify_spectral.py --ref       # build the float64 mordred reference only
    .venv/bin/python verify_spectral.py --no-ref    # skip it (float32 grade only, no mordred)
    .venv/bin/python verify_spectral.py --shuffle   # + the atom-renumbering stability probe
    .venv/bin/python verify_spectral.py --limit N   # first N corpus molecules only

NO DESCRIPTOR VALUE IS COMPUTED IN PYTHON HERE (contract rule 1). This file does three things:
it serialises the corpus into a binary blob, it shells out to a C++ driver that includes
spectral.h and nothing else of ours, and it compares the driver's doubles against reference
values that came out of mordred itself.

WHY THERE ARE TWO REFERENCES, and this is the first finding of the exercise.
`data/dedupe2/matrix.npz` stores `MD` as **float32**. A float32 cell carries ~7 significant
decimal digits, so "bit-identical" against it is a statement about the first 24 bits of a
double and the contract's 1e-9 tier cannot be evaluated at all. The npz is therefore used as
the FULL-CORPUS check (all 20,000 molecules, 65 columns, including every NaN), and a float64
reference is regenerated from mordred 1.2.0 for the same corpus and cached in the scratchpad;
that one carries the exactness grade. The two are cross-checked against each other so the
regeneration cannot silently be of a different quantity.

The driver is GENERATED into build_spectral/ rather than committed, because the contract
confines this agent to three files and a build directory. It is a build artefact: delete
build_spectral/ and this script reproduces it.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build_spectral"
SCRATCH = Path(os.environ.get(
    "SPECTRAL_SCRATCH",
    "/private/tmp/claude-501/-Users-lsieben-VSCode-universal-encoder/"
    "0bcd394f-baf3-4dc2-8547-cc0dc82592fe/scratchpad"))
MORDRED_PY = ROOT / ".venv-mordred" / "bin" / "python"

COLS = ['SpAbs_A', 'SpMax_A', 'SpDiam_A', 'SpMAD_A', 'VE1_A', 'VE2_A', 'VE3_A', 'VR1_A',
        'VR2_A', 'VR3_A', 'BCUTc-1h', 'BCUTc-1l', 'BCUTdv-1h', 'BCUTdv-1l', 'BCUTd-1h',
        'BCUTd-1l', 'BCUTs-1h', 'BCUTs-1l', 'BCUTZ-1h', 'BCUTZ-1l', 'BCUTv-1h', 'BCUTv-1l',
        'BCUTse-1h', 'BCUTse-1l', 'BCUTpe-1l', 'BCUTare-1l', 'BCUTp-1h', 'BCUTp-1l',
        'BCUTi-1h', 'BCUTi-1l', 'SpAbs_DzZ', 'SpDiam_DzZ', 'SpMAD_DzZ', 'SM1_DzZ', 'VE1_DzZ',
        'VE2_DzZ', 'VR1_DzZ', 'VR2_DzZ', 'SpAbs_Dzv', 'SpDiam_Dzv', 'SpMAD_Dzv', 'SM1_Dzv',
        'VE1_Dzv', 'VE2_Dzv', 'VR2_Dzv', 'VR3_Dzv', 'SpAbs_Dzse', 'SpDiam_Dzse', 'SpMAD_Dzse',
        'SM1_Dzse', 'SM1_Dzare', 'SpAbs_Dzp', 'SpDiam_Dzp', 'SpMAD_Dzp', 'SM1_Dzp', 'VE1_Dzp',
        'VE2_Dzp', 'SpAbs_Dzi', 'SpMAD_Dzi', 'SM1_Dzi', 'SpAbs_D', 'SpDiam_D', 'SpMAD_D',
        'VE1_D', 'VE2_D']
NC = len(COLS)

C_MISSING = -1e30          # ac_weights.h's AC_C_MISSING sentinel

# --------------------------------------------------------------------------- the C++ driver

DRIVER = r"""
// GENERATED by verify_spectral.py. Not part of the package; a harness that includes
// src/hume_core/spectral.h and nothing else of HUME's, reads the binary corpus blob the script
// wrote, and dumps 65 raw doubles per molecule plus a per-molecule nanosecond timing.
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

#include "spectral.h"

template <class T>
static void rd(std::FILE *f, T *p, std::size_t n) {
  if (std::fread(p, sizeof(T), n, f) != n) { std::fprintf(stderr, "short read\n"); std::exit(2); }
}

int main(int argc, char **argv) {
  if (argc < 4) { std::fprintf(stderr, "usage: driver in.bin out.bin time.bin [reps]\n"); return 2; }
  const int reps = (argc > 4) ? std::atoi(argv[4]) : 1;
  std::FILE *f = std::fopen(argv[1], "rb");
  if (!f) { std::perror(argv[1]); return 2; }
  std::int32_t nmol = 0, na = 0, nb = 0;
  rd(f, &nmol, 1); rd(f, &na, 1); rd(f, &nb, 1);
  std::vector<std::int32_t> aoff(nmol + 1), boff(nmol + 1), az(na), afc(na), anh(na),
      bu(nb), bv(nb);
  std::vector<double> ac(na), bo(nb);
  rd(f, aoff.data(), nmol + 1); rd(f, boff.data(), nmol + 1);
  rd(f, az.data(), na); rd(f, afc.data(), na); rd(f, anh.data(), na); rd(f, ac.data(), na);
  rd(f, bu.data(), nb); rd(f, bv.data(), nb); rd(f, bo.data(), nb);
  std::fclose(f);

  std::vector<double> out((std::size_t)nmol * spectral::N_COLS), tim(nmol);
  spectral::Scratch S;
  spectral::Mol m;
  for (int k = 0; k < nmol; k++) {
    const int a0 = aoff[k], b0 = boff[k];
    m.n = aoff[k + 1] - a0;
    m.nb = boff[k + 1] - b0;
    m.at.assign(m.n, AtomRec());
    for (int i = 0; i < m.n; i++) {
      m.at[i].z = az[a0 + i]; m.at[i].fc = afc[a0 + i];
      m.at[i].nh = anh[a0 + i]; m.at[i].c = ac[a0 + i];
    }
    m.bu.assign(bu.begin() + b0, bu.begin() + boff[k + 1]);
    m.bv.assign(bv.begin() + b0, bv.begin() + boff[k + 1]);
    m.bord.assign(bo.begin() + b0, bo.begin() + boff[k + 1]);
    m.adj.assign(m.n, std::vector<int>());
    for (int b = 0; b < m.nb; b++) {
      m.adj[m.bu[b]].push_back(m.bv[b]);
      m.adj[m.bv[b]].push_back(m.bu[b]);
    }
    double *o = &out[(std::size_t)k * spectral::N_COLS];
    // MINIMUM over repetitions, not the mean. Five agents build and test in this checkout at
    // once and the load average reaches 130; a mean is then a measurement of the other agents.
    // The minimum is the only statistic that survives that, and it is what the run reports.
    double best = 1e300;
    for (int r = 0; r < reps; r++) {
      const auto t0 = std::chrono::steady_clock::now();
      spectral::compute(m, o, S);
      const auto t1 = std::chrono::steady_clock::now();
      const double dt = std::chrono::duration<double, std::nano>(t1 - t0).count();
      if (dt < best) best = dt;
    }
    tim[k] = best;
  }
  std::FILE *g = std::fopen(argv[2], "wb");
  std::fwrite(out.data(), sizeof(double), out.size(), g);
  std::fclose(g);
  g = std::fopen(argv[3], "wb");
  std::fwrite(tim.data(), sizeof(double), tim.size(), g);
  std::fclose(g);
  // The one guard in spectral.h that can silently not fire. Printed, not assumed. Divided by
  // `reps` because every molecule is computed that many times for the timing.
  std::fprintf(stderr, "leading_vector shift retries: %lld per pass over %d molecules\n",
               spectral::detail::shift_retries() / reps, nmol);
  return 0;
}
"""

# --------------------------------------------------------------------------- corpus -> blob


def serialise(smis, path, perm_seed=None):
    """Write the binary corpus blob the driver reads. RDKit only; no descriptor arithmetic.

    `perm_seed` RENUMBERS every molecule's atoms with a random permutation. All 65 columns are
    permutation invariants in exact arithmetic (every matrix here is permutation-SIMILAR under a
    renumbering, and VE1/VR1 are symmetric functions of the leading eigenvector), so the spread
    across seeds is a direct measurement of how much of each column is floating-point noise
    rather than molecule. See `--shuffle`.
    """
    from rdkit import Chem, RDLogger
    from rdkit.Chem import rdPartialCharges
    RDLogger.DisableLog("rdApp.*")

    rng = np.random.default_rng(perm_seed) if perm_seed is not None else None
    aoff, boff = [0], [0]
    az, afc, anh, ac, bu, bv, bo = [], [], [], [], [], [], []
    order_cache = {}
    for s in smis:
        m = Chem.MolFromSmiles(s)
        if m is None:
            raise ValueError(f"corpus SMILES did not parse: {s!r}")
        # mordred's Context hands explicit_hydrogens=False descriptors RemoveHs(mol, True).
        m = Chem.RemoveHs(m, updateExplicitCount=True)
        # mordred's AtomicProperty.calculate() runs this on its own molecule with RDKit's
        # default nIter; an exception there leaves the properties unset, which mordred turns
        # into an Error and the reference matrix into NaN. The sentinel reproduces that.
        ok = True
        try:
            rdPartialCharges.ComputeGasteigerCharges(m)
        except Exception:
            ok = False
        n = m.GetNumAtoms()
        new = rng.permutation(n) if rng is not None else np.arange(n)   # old index -> new index
        old = np.empty(n, int)
        old[new] = np.arange(n)                                         # new index -> old index
        atoms = [m.GetAtomWithIdx(int(i)) for i in old]
        for a in atoms:
            az.append(a.GetAtomicNum())
            afc.append(a.GetFormalCharge())
            anh.append(a.GetTotalNumHs())
            if not ok:
                ac.append(C_MISSING)
                continue
            # mordred's `c` getter, verbatim: the sum is INSIDE the conditional.
            try:
                q = (a.GetDoubleProp("_GasteigerCharge") + a.GetDoubleProp("_GasteigerHCharge")
                     if a.HasProp("_GasteigerHCharge") else 0.0)
            except Exception:
                q = C_MISSING
            ac.append(q)
        bonds = list(m.GetBonds())
        if rng is not None:
            bonds = [bonds[i] for i in rng.permutation(len(bonds))]
        for b in bonds:
            bu.append(int(new[b.GetBeginAtomIdx()]))
            bv.append(int(new[b.GetEndAtomIdx()]))
            bt = b.GetBondType()
            o = order_cache.get(bt)
            if o is None:
                o = order_cache[bt] = b.GetBondTypeAsDouble()
            bo.append(o)
        aoff.append(len(az))
        boff.append(len(bu))

    with open(path, "wb") as f:
        np.array([len(smis), len(az), len(bu)], np.int32).tofile(f)
        np.array(aoff, np.int32).tofile(f)
        np.array(boff, np.int32).tofile(f)
        np.array(az, np.int32).tofile(f)
        np.array(afc, np.int32).tofile(f)
        np.array(anh, np.int32).tofile(f)
        np.array(ac, np.float64).tofile(f)
        np.array(bu, np.int32).tofile(f)
        np.array(bv, np.int32).tofile(f)
        np.array(bo, np.float64).tofile(f)
    return path


# --------------------------------------------------------------------------- float64 mordred

REF_SCRIPT = r"""
import json, sys, numpy as np
from rdkit import Chem, RDLogger
RDLogger.DisableLog("rdApp.*")
from mordred import Calculator
from mordred import AdjacencyMatrix, BCUT, BaryszMatrix, DistanceMatrix


def main():
    WANT = json.load(open(sys.argv[2]))
    calc = Calculator()
    calc.register(AdjacencyMatrix)
    calc.register(BCUT)
    calc.register(BaryszMatrix)
    calc.register(DistanceMatrix)
    names = [str(d) for d in calc.descriptors]
    idx = [names.index(c) for c in WANT]

    smis = json.load(open(sys.argv[1]))["smiles"]
    mols = [Chem.MolFromSmiles(s) for s in smis]
    rows = []
    for r in calc.map(mols, nproc=int(sys.argv[4]), quiet=True):
        v = list(r.values())
        rows.append([float(v[j]) if isinstance(v[j], (int, float)) else float("nan")
                     for j in idx])
    np.save(sys.argv[3], np.asarray(rows, dtype=np.float64))


if __name__ == "__main__":
    main()
"""


def build_reference(limit, allow_build=True):
    SCRATCH.mkdir(parents=True, exist_ok=True)
    out = SCRATCH / f"mordred_f64_{limit or 'all'}.npy"
    if out.exists():
        return out
    if not allow_build:
        return None
    if not MORDRED_PY.exists():
        raise SystemExit(f"{MORDRED_PY} not found; cannot build the float64 reference")
    corpus = ROOT / "data" / "dedupe2" / "corpus.json"
    if limit:
        d = json.load(open(corpus))
        corpus = SCRATCH / f"corpus_{limit}.json"
        json.dump({"smiles": d["smiles"][:limit]}, open(corpus, "w"))
    want = SCRATCH / "want.json"
    json.dump(COLS, open(want, "w"))
    script = SCRATCH / "gen_ref.py"
    script.write_text(REF_SCRIPT)
    t0 = time.time()
    print(f"  running mordred 1.2.0 for {NC} columns "
          f"({limit or 20000} molecules, nproc=10) ...", flush=True)
    subprocess.run([str(MORDRED_PY), str(script), str(corpus), str(want), str(out), "10"],
                   check=True, cwd=str(ROOT))
    print(f"  -> {out}  ({time.time() - t0:.0f}s)")
    return out


# --------------------------------------------------------------------------- grading


def relerr(a, b):
    """Relative difference of two float64 vectors, with the equal/inf cases pinned to zero.

    The denominator is |reference|, or 1 where the reference is 0 -- an absolute error there,
    which is the only meaningful thing to quote against an exact zero.
    """
    rel = np.zeros(a.shape)
    eq = (a == b) | (np.isinf(a) & np.isinf(b) & (np.sign(a) == np.sign(b)))
    den = np.where(b != 0, np.abs(b), 1.0)
    with np.errstate(invalid="ignore", over="ignore"):
        rel = np.abs(a - b) / den
    rel[eq] = 0.0
    rel[np.isnan(rel)] = np.inf          # one finite, one infinite: a real disagreement
    return rel


# The six columns of the DOCUMENTED divergence (NOTES_spectral.md section 4): they are built
# from the adjacency matrix's leading eigenvector, which double precision cannot resolve on a
# molecule whose two halves are near-identical. mordred's value there is not a function of the
# molecule -- it moves with the atom numbering, with the thread count, and between runs of
# mordred itself -- and ours is measurably closer to a 60-digit reference. Disagreement HERE is
# expected and is reported; disagreement anywhere else is a regression and fails the run.
DIVERGENT = {"VE1_A", "VE2_A", "VE3_A", "VR1_A", "VR2_A", "VR3_A"}


def grade(ours, ref, smis, tag, per_col_examples=3):
    """Per-column counts against a float64 reference. Both arrays are (nmol, 65).

    Returns (total mismatched cells, mismatched cells outside the six documented columns).
    """
    print()
    print(f"=== {tag} ===")
    print(f"{'column':<14}{'bitexact':>9}{'<=1e-9':>8}{'<=1e-6':>8}{'MISMATCH':>9}"
          f"{'nanOK':>7}{'nanX':>6}   worst rel")
    mismatches = []
    total_bad = 0
    unexpected = 0
    for j, c in enumerate(COLS):
        a, b = ours[:, j], ref[:, j]
        na, nb = np.isnan(a), np.isnan(b)
        nan_agree = int((na & nb).sum())
        nan_only = np.flatnonzero(na ^ nb)
        both = np.flatnonzero(~na & ~nb)
        av, bv = a[both], b[both]
        rel = relerr(av, bv)
        bits = av == bv                                   # bit-identical, NaN already excluded
        e9, e6 = rel <= 1e-9, rel <= 1e-6
        bad_idx = both[~e6]
        bad = len(bad_idx) + len(nan_only)
        total_bad += bad
        if c not in DIVERGENT:
            unexpected += bad
        wr = float(rel.max()) if rel.size else 0.0
        print(f"{c:<14}{int(bits.sum()):>9}{int(e9.sum()):>8}{int(e6.sum()):>8}"
              f"{bad:>9}{nan_agree:>7}{len(nan_only):>6}   {wr:.3e}")
        for i in list(bad_idx[np.argsort(-rel[~e6])][:per_col_examples]) + list(nan_only)[:3]:
            mismatches.append((c, smis[i], ref[i, j], ours[i, j]))
    print(f"\ncells outside 1e-6 relative or disagreeing on NaN: {total_bad} "
          f"of {ours.size}")
    print(f"  of which in the six documented divergent columns "
          f"({', '.join(sorted(DIVERGENT))}): {total_bad - unexpected}")
    print(f"  of which UNEXPECTED (any other column):                     {unexpected}")
    if mismatches:
        print("\nmismatches (column, SMILES, reference, ours):")
        for c, s, r, o in mismatches[:200]:
            print(f"  {c:<12} {s[:64]:<64} ref={r!r:<25} ours={o!r}")
    return total_bad, unexpected


# --------------------------------------------------------------------------- main


def build_driver():
    BUILD.mkdir(exist_ok=True)
    src = BUILD / "spectral_main.cpp"
    src.write_text(DRIVER)
    exe = BUILD / "spectral_driver"
    cmd = ["c++", "-O3", "-std=c++17", f"-I{ROOT / 'src' / 'hume_core'}",
           str(src), "-o", str(exe)]
    print("  " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)
    return exe


def run_driver(exe, smis, tag, reps=1, perm_seed=None):
    blob = BUILD / f"corpus_{tag}.bin"
    serialise(smis, blob, perm_seed)
    outb, timb = BUILD / f"out_{tag}.bin", BUILD / f"time_{tag}.bin"
    subprocess.run([str(exe), str(blob), str(outb), str(timb), str(reps)], check=True)
    return (np.fromfile(outb, np.float64).reshape(len(smis), NC),
            np.fromfile(timb, np.float64))


def shuffle_probe(exe, smis, base, seeds=(1, 2, 3, 4)):
    """How much of each column is the molecule and how much is the atom numbering?

    Every one of the 65 is a permutation invariant in exact arithmetic. Anything that moves
    when the atoms are renumbered is floating-point noise, and its size is the honest
    resolution of that column. This is the same screen `_extract.py` describes for the
    stereo columns, applied to a family whose small eigenvector entries make it necessary.
    """
    print("\n=== atom-renumbering stability (this implementation, 4 random relabellings) ===")
    runs = [base]
    for s in seeds:
        v, _ = run_driver(exe, smis, f"shuf{s}", 1, perm_seed=s)
        runs.append(v)
    A = np.stack(runs)                                   # (1+len(seeds), nmol, 65)
    print(f"{'column':<14}{'moved':>8}{'>1e-9':>8}{'>1e-6':>8}   worst rel   worst SMILES")
    worst = {}
    for j, c in enumerate(COLS):
        col = A[:, :, j]
        with np.errstate(invalid="ignore"):
            lo, hi = np.nanmin(col, 0), np.nanmax(col, 0)
            den = np.where(np.abs(lo) > 0, np.abs(lo), 1.0)
            spread = np.abs(hi - lo) / den
        spread[np.isnan(spread)] = 0.0
        moved = int((spread > 0).sum())
        k = int(np.argmax(spread))
        worst[c] = float(spread[k])
        print(f"{c:<14}{moved:>8}{int((spread > 1e-9).sum()):>8}"
              f"{int((spread > 1e-6).sum()):>8}   {spread[k]:.3e}   {smis[k][:44]}")
    return worst


def main():
    limit = None
    do_ref_only = "--ref" in sys.argv
    do_shuffle = "--shuffle" in sys.argv
    skip_ref = "--no-ref" in sys.argv
    args = sys.argv[1:]
    if "--limit" in args:
        limit = int(args[args.index("--limit") + 1])

    BUILD.mkdir(exist_ok=True)
    d = json.load(open(ROOT / "data" / "dedupe2" / "corpus.json"))
    smis = d["smiles"]
    strat = d["stratum"]
    if limit:
        smis, strat = smis[:limit], strat[:limit]
    print(f"{len(smis):,} molecules, {NC} columns")

    ref64 = build_reference(limit, allow_build=not skip_ref)
    if do_ref_only:
        return

    exe = build_driver()
    print("  serialising corpus ...", flush=True)
    reps = 3
    ours, tim = run_driver(exe, smis, "main", reps)

    # ---- against the shipped float32 matrix: FULL coverage, ~7 digits of resolution
    z = np.load(ROOT / "data" / "dedupe2" / "matrix.npz", allow_pickle=True)
    md = list(z["md_names"])
    R32 = z["MD"][:len(smis)][:, [md.index(c) for c in COLS]].astype(np.float64)
    o32 = ours.astype(np.float32).astype(np.float64)
    same = (o32 == R32) | (np.isnan(o32) & np.isnan(R32))
    bad32, unexp = grade(o32, R32, smis,
                         "data/dedupe2/matrix.npz (float32 -- both sides rounded)")
    print(f"  float32-identical cells: {int(same.sum())} of {same.size} "
          f"({100.0 * same.sum() / same.size:.4f}%)")

    # ---- grade against the float64 mordred reference (the exactness bar)
    if ref64 is None:
        print("\n(no float64 mordred reference yet -- run with --ref)")
    else:
        R64 = np.load(ref64)
        _, unexp = grade(ours, R64, smis, "float64 mordred 1.2.0 reference")
        d32 = np.abs(R32 - R64.astype(np.float32).astype(np.float64))
        n_diff = int(np.nansum(d32 > 0))
        nan_diff = int((np.isnan(R32) ^ np.isnan(R64)).sum())
        print(f"\ncross-check: the regenerated float64 reference, rounded back to float32, "
              f"differs from data/dedupe2/matrix.npz in {n_diff} of {R32.size} cells; the NaN "
              f"pattern differs in {nan_diff}.")

    # ---- timing
    us = tim / 1000.0
    print(f"\nper-molecule timing (best of {reps}, single thread; "
          f"load average at the time: {os.getloadavg()[0]:.0f})")
    print(f"{'stratum':<14}{'n mols':>8}{'us/mol':>12}{'SD':>10}{'median':>10}{'max':>10}")
    order = ["0-15", "15-25", "25-35", "35-55", "55-1000000"]
    for s in order:
        k = np.array([x == s for x in strat])
        if not k.any():
            continue
        v = us[k]
        print(f"{s:<14}{k.sum():>8}{v.mean():>12.1f}{v.std():>10.1f}"
              f"{np.median(v):>10.1f}{v.max():>10.1f}")
    print(f"{'ALL':<14}{len(us):>8}{us.mean():>12.1f}{us.std():>10.1f}"
          f"{np.median(us):>10.1f}{us.max():>10.1f}")

    if do_shuffle:
        shuffle_probe(exe, smis, ours)

    # The run FAILS on a mismatch outside the six documented columns, and only on that. The
    # divergence in those six is deliberate, measured and argued in NOTES_spectral.md section 4;
    # a silent regression anywhere else is what this exit code is for.
    print("\nVERDICT: " + ("PASS -- every disagreement with mordred is inside the six "
                           "documented divergent columns"
                           if unexp == 0 else
                           f"FAIL -- {unexp} mismatched cells OUTSIDE the documented divergence"))
    sys.exit(1 if unexp else 0)


if __name__ == "__main__":
    main()
