#!/usr/bin/env python
"""Verification harness for src/hume_core/estate_ext.h -- group D_estate, 22 columns.

    .venv/bin/python verify_estate.py            dump, build, run, grade, time
    .venv/bin/python verify_estate.py --keep     as above, keep the intermediate text files

HOUSE RULE 1: NOTHING HERE COMPUTES A DESCRIPTOR VALUE. This script

  * reads the molecules out of data/dedupe2/corpus.json and marshals RDKit's graph
    (atomic number, degree, H count, aromatic flag, bond type) into a text file,
  * emits, compiles and runs a small C++ driver that calls estate_ext::compute(),
  * reads the reference values out of data/dedupe2/matrix.npz,
  * and compares.

The driver is written into build_estate/ rather than into the repository because the
group's contract limits the files this agent may create; it is regenerated on every run,
so there is no stale copy to drift.

THE REFERENCE IS float32. data/dedupe2/matrix.npz stores mordred's answers as float32, so
"bit-identical" is asked in float32 space: np.float32(ours) has the same bit pattern as the
stored value. The relative bands (1e-9, 1e-6) are reported on top of that, and NaN agreement
is counted separately from numeric agreement, per the contract.
"""

import json
import os
import subprocess
import sys
import time

import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(ROOT, "build_estate")

COLS = [
    "SZ",
    "MAXsCH3", "MAXssCH2", "MAXaaCH", "MAXsssCH", "MAXdssC", "MAXaasC", "MAXssNH", "MAXdO",
    "MINsCH3", "MINssCH2", "MINaaCH", "MINsssCH", "MINdssC", "MINaasC", "MINssNH", "MINdO",
    "SRW04", "SRW06", "SRW08", "SRW09", "SRW10",
]
# The `N<t>` companion of each MAX/MIN column. mordred's docstring says MAX/MIN is NaN exactly
# when N<t> == 0; that implication is checked, not assumed.
EXT_TYPES = ["sCH3", "ssCH2", "aaCH", "sssCH", "dssC", "aasC", "ssNH", "dO"]

MORDRED_PY = os.path.join(ROOT, ".venv-mordred/bin/python")

# Mordred, live, in float64 -- on a 1-in-STRIDE subsample of the same corpus.
#
# WHY THIS IS HERE AND NOT LEFT TO matrix.npz. The stored reference is float32, which rounds away
# roughly 29 bits of every value. Grading only against it would report these 22 columns as
# essentially exact and hide a real last-bit disagreement in the sixteen MAX/MIN columns -- the
# contract's bar is exactness, so the harness has to ask the question at the precision mordred
# actually answers it in. Only the 22 descriptor objects of this group are registered, so this
# runs in seconds rather than the tens of minutes a full Calculator would take.
MORDRED_F64 = r"""
import json, sys
from rdkit import Chem
from mordred import Calculator
from mordred.EState import AtomTypeEState
from mordred.Constitutional import ConstitutionalSum
from mordred.WalkCount import WalkCount

corpus, stride, outp = sys.argv[1], int(sys.argv[2]), sys.argv[3]
TYPES = %(types)r
ds = [ConstitutionalSum('Z')]
ds += [AtomTypeEState('max', t) for t in TYPES]
ds += [AtomTypeEState('min', t) for t in TYPES]
ds += [WalkCount(k, False, True) for k in (4, 6, 8, 9, 10)]
calc = Calculator()
for d in ds:
    calc.register(d)
names = [str(d) for d in calc.descriptors]
smis = json.load(open(corpus))['smiles'][::stride]
vals = []
for s in smis:
    row = []
    for v in calc(Chem.MolFromSmiles(s)):
        try:
            row.append(float(v))
        except Exception:
            row.append(float('nan'))
    vals.append(row)
json.dump({'cols': names, 'vals': vals}, open(outp, 'w'))
""" % dict(types=EXT_TYPES)


# ---------------------------------------------------------------------------------------------
# the C++ driver
# ---------------------------------------------------------------------------------------------
DRIVER = r"""
// GENERATED by verify_estate.py -- regenerated on every run, do not edit.
//
// Reads the text dump verify_estate.py writes, rebuilds the two molecule structs that already
// exist in bindings.cpp (esttyper::Mol for the typer, the hume_blocks Mol for the per-atom
// E-state index), and calls estate_ext::compute(). Prints one line of 22 %.17g values per
// molecule, or -- in `bench` mode -- the per-molecule cost of compute() alone.
//
// A third argument `rdkitorder` swaps hume_blocks.h's estate_from() for the SAME arithmetic in
// RDKit's own accumulation order -- deltas into a zero array, `Is` added once at the end, which
// is literally `res = accum + Is` in rdkit/Chem/EState/EState.py. This is a DIAGNOSTIC, not a
// second implementation: it exists to attribute this group's only three mismatched cells, and
// NOTES_estate.md reports what it shows. estate_ext.h itself never computes an index.
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include "../src/hume_core/hume_blocks.h"
#include "../src/hume_core/estate_ext.h"

struct Rec {
  int n = 0, nb = 0;
  std::vector<int> z, deg, nh, ar, bu, bv, bt;
};

static std::vector<Rec> load(const char *path) {
  FILE *f = std::fopen(path, "r");
  if (!f) { std::fprintf(stderr, "estate_ext driver: cannot open %s\n", path); std::exit(1); }
  int nm = 0;
  if (std::fscanf(f, "%d", &nm) != 1) { std::fprintf(stderr, "bad header\n"); std::exit(1); }
  std::vector<Rec> out((size_t)nm);
  for (int k = 0; k < nm; ++k) {
    Rec &r = out[(size_t)k];
    if (std::fscanf(f, "%d %d", &r.n, &r.nb) != 2) {
      std::fprintf(stderr, "estate_ext driver: truncated at molecule %d\n", k); std::exit(1);
    }
    r.z.resize(r.n); r.deg.resize(r.n); r.nh.resize(r.n); r.ar.resize(r.n);
    for (int i = 0; i < r.n; ++i)
      if (std::fscanf(f, "%d %d %d %d", &r.z[i], &r.deg[i], &r.nh[i], &r.ar[i]) != 4) {
        std::fprintf(stderr, "estate_ext driver: truncated atom %d of molecule %d\n", i, k);
        std::exit(1);
      }
    r.bu.resize(r.nb); r.bv.resize(r.nb); r.bt.resize(r.nb);
    for (int b = 0; b < r.nb; ++b)
      if (std::fscanf(f, "%d %d %d", &r.bu[b], &r.bv[b], &r.bt[b]) != 3) {
        std::fprintf(stderr, "estate_ext driver: truncated bond %d of molecule %d\n", b, k);
        std::exit(1);
      }
  }
  std::fclose(f);
  return out;
}

// Exactly the fill bindings.cpp performs, so the driver exercises the wiring it documents.
static void build(const Rec &r, esttyper::Mol &em, Mol &hm) {
  em.alloc(r.n, 2 * r.nb);
  for (int i = 0; i < r.n; ++i) {
    em.z[i] = (uint8_t)(r.z[i] > 255 ? 255 : r.z[i]);
    em.nH[i] = (uint8_t)r.nh[i];
    em.arom[i] = (uint8_t)r.ar[i];
  }
  for (int b = 0; b < r.nb; ++b) { em.start[r.bu[b] + 1]++; em.start[r.bv[b] + 1]++; }
  for (int i = 0; i < r.n; ++i) em.start[i + 1] += em.start[i];
  std::vector<int32_t> cur(em.start.begin(), em.start.end() - 1);
  for (int b = 0; b < r.nb; ++b) {
    const uint8_t t = (uint8_t)r.bt[b];
    em.nbr[cur[r.bu[b]]] = r.bv[b]; em.btype[cur[r.bu[b]]++] = t;
    em.nbr[cur[r.bv[b]]] = r.bu[b]; em.btype[cur[r.bv[b]]++] = t;
  }
  em.finish();
  for (int i = 0; i < r.n; ++i)
    if (em.deg(i) != r.deg[i]) {
      std::fprintf(stderr, "estate_ext driver: CSR degree %d != RDKit GetDegree %d at atom %d\n",
                   em.deg(i), r.deg[i], i);
      std::exit(1);
    }

  hm.n = r.n;
  hm.nb = r.nb;
  hm.Z.assign(r.z.begin(), r.z.end());
  hm.deg.assign(r.deg.begin(), r.deg.end());
  hm.nH.assign(r.nh.begin(), r.nh.end());
  hm.adj.assign(r.n, std::vector<int>());
  for (int b = 0; b < r.nb; ++b) {
    hm.adj[r.bu[b]].push_back(r.bv[b]);
    hm.adj[r.bv[b]].push_back(r.bu[b]);
  }
}

// rdkit/Chem/EState/EState.py's own order, for the attribution diagnostic described above.
// Same terms, same distance matrix, same I; only `accum` starts at zero and `Is` is added once.
static void estate_rdkit_order(const Mol &m, const std::vector<int> &D, std::vector<double> &S) {
  const int n = m.n;
  std::vector<double> I(n, 0.0);
  S.assign(n, 0.0);
  for (int i = 0; i < n; ++i) {
    if (m.deg[i] <= 0) continue;
    double dv = n_outer(m.Z[i]) - m.nH[i];
    double N = principal_qn(m.Z[i]);
    I[i] = (4.0 / (N * N) * dv + 1.0) / m.deg[i];
  }
  for (int i = 0; i < n; ++i)
    for (int j = i + 1; j < n; ++j) {
      double p = D[(size_t)i * n + j] + 1.0;
      if (p < 1e6) { double t = (I[i] - I[j]) / (p * p); S[i] += t; S[j] -= t; }
    }
  for (int i = 0; i < n; ++i) S[i] += I[i];
}

int main(int argc, char **argv) {
  if (argc < 3) { std::fprintf(stderr, "usage: drv <in> <out> [rdkitorder] | drv bench <in> [reps]\n"); return 1; }
  const bool bench = std::strcmp(argv[1], "bench") == 0;
  const bool rdorder = argc > 3 && std::strcmp(argv[3], "rdkitorder") == 0;
  const char *inp = bench ? argv[2] : argv[1];
  std::vector<Rec> mols = load(inp);

  esttyper::selfCheck();

  esttyper::Mol em;
  Mol hm;
  std::vector<int> D;
  std::vector<double> ES;
  estate_ext::Scratch S;
  double out[estate_ext::N_COLS];

  if (!bench) {
    FILE *g = std::fopen(argv[2], "w");
    if (!g) { std::fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
    for (size_t k = 0; k < mols.size(); ++k) {
      build(mols[k], em, hm);
      distances(hm, D);
      if (rdorder) estate_rdkit_order(hm, D, ES); else estate_from(hm, D, ES);
      estate_ext::compute(em, ES.data(), out, S);
      for (int c = 0; c < estate_ext::N_COLS; ++c)
        std::fprintf(g, c ? " %.17g" : "%.17g", out[c]);
      std::fputc('\n', g);
    }
    std::fclose(g);
    return 0;
  }

  const int reps = argc > 3 ? std::atoi(argv[3]) : 5;
  // Per-molecule cost of compute() ALONE. estate_from()/distances() are excluded on purpose:
  // both are already paid for by the columns HUME ships today, so what this group ADDS is the
  // reduction, not the index.
  std::vector<double> best(mols.size(), 1e300);
  for (int rep = 0; rep < reps; ++rep) {
    for (size_t k = 0; k < mols.size(); ++k) {
      build(mols[k], em, hm);
      distances(hm, D);
      estate_from(hm, D, ES);
      auto t0 = std::chrono::steady_clock::now();
      estate_ext::compute(em, ES.data(), out, S);
      auto t1 = std::chrono::steady_clock::now();
      double us = std::chrono::duration<double, std::micro>(t1 - t0).count();
      if (us < best[k]) best[k] = us;
      if (out[0] == 1e300) std::fprintf(stderr, "");   // keep the call live
    }
  }
  for (size_t k = 0; k < mols.size(); ++k) std::printf("%.4f\n", best[k]);
  return 0;
}
"""


# ---------------------------------------------------------------------------------------------
# marshalling
# ---------------------------------------------------------------------------------------------
def dump(smiles, path):
    """RDKit's graph as text. No descriptor is computed here -- these are the five per-atom /
    per-bond facts bindings.cpp already reads out of the pickle (A_Z, A_DEG, A_NH, A_AROM,
    B_CODE), written in the same atom and bond order RDKit itself uses."""
    from rdkit import Chem
    from rdkit.Chem import rdchem

    # esttyper::BT_* -- the bond TYPE alone, which is the question RDKit's own E-state SMARTS
    # ask (`:` is a bond-order query, not getIsAromatic()). Anything else is 0, matching
    # esttyper::btypeFromBcode's fallthrough.
    BT = {
        rdchem.BondType.SINGLE: 1,
        rdchem.BondType.DOUBLE: 2,
        rdchem.BondType.TRIPLE: 4,
        rdchem.BondType.AROMATIC: 8,
    }
    mols = []
    with open(path, "w") as f:
        f.write("%d\n" % len(smiles))
        for smi in smiles:
            m = Chem.MolFromSmiles(smi)
            if m is None:
                raise RuntimeError("verify_estate: RDKit could not parse corpus SMILES %r" % smi)
            mols.append(m)
            f.write("%d %d\n" % (m.GetNumAtoms(), m.GetNumBonds()))
            for a in m.GetAtoms():
                f.write("%d %d %d %d\n" % (a.GetAtomicNum(), a.GetDegree(),
                                           a.GetTotalNumHs(False), int(a.GetIsAromatic())))
            for b in m.GetBonds():
                f.write("%d %d %d\n" % (b.GetBeginAtomIdx(), b.GetEndAtomIdx(),
                                        BT.get(b.GetBondType(), 0)))
    return mols


def build_driver():
    os.makedirs(BUILD, exist_ok=True)
    src = os.path.join(BUILD, "estate_ext_drv.cpp")
    exe = os.path.join(BUILD, "estate_ext_drv")
    with open(src, "w") as f:
        f.write(DRIVER)
    cmd = ["c++", "-std=c++17", "-O3", "-o", exe, src]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verify_estate: driver failed to compile (%s)" % " ".join(cmd))
    return exe


# ---------------------------------------------------------------------------------------------
# grading
# ---------------------------------------------------------------------------------------------
def grade(ours, ref, smiles, strata):
    """Per column: exact / 1e-9 / 1e-6 / mismatch, with NaN agreement counted separately."""
    n = len(smiles)
    f32 = ours.astype(np.float32)
    report = []
    worst = {}
    for j, name in enumerate(COLS):
        a, b = f32[:, j], ref[:, j]
        na, nb = np.isnan(a), np.isnan(b)
        both_nan = int((na & nb).sum())
        nan_dis = np.where(na != nb)[0]
        fin = ~na & ~nb
        af = np.ascontiguousarray(a[fin])
        bf = np.ascontiguousarray(b[fin])
        exact = int((af.view(np.int32) == bf.view(np.int32)).sum())
        d = np.abs(af.astype(np.float64) - bf.astype(np.float64))
        scale = np.maximum(np.abs(bf.astype(np.float64)), 1e-300)
        rel = d / scale
        w9 = int((rel <= 1e-9).sum())
        w6 = int((rel <= 1e-6).sum())
        bad = np.where(rel > 1e-6)[0]
        idx_fin = np.where(fin)[0]
        mismatch = [int(i) for i in idx_fin[bad]] + [int(i) for i in nan_dis]
        report.append(dict(name=name, n=n, exact=exact, w9=w9, w6=w6,
                           nan_both=both_nan, nan_dis=len(nan_dis),
                           nmis=len(mismatch), finite=int(fin.sum())))
        worst[name] = mismatch[:10]
    return report, worst


STRIDE = 20


def float64_check(exe, dumpf, ours, ours2, keep):
    """Bit-exactness against a LIVE mordred, in float64, on every STRIDE-th molecule.

    Returns True if any column is not bit-identical under either index order. `ours` is the
    shipped path (hume_blocks.h estate_from); `ours2` is the same 22 reductions over an index
    accumulated in RDKit's order."""
    if not os.path.exists(MORDRED_PY):
        print("\nfloat64 cross-check SKIPPED: no %s" % MORDRED_PY)
        return False
    script = os.path.join(BUILD, "mordred_f64.py")
    jsn = os.path.join(BUILD, "mordred_f64.json")
    with open(script, "w") as f:
        f.write(MORDRED_F64)
    t0 = time.time()
    r = subprocess.run([MORDRED_PY, script,
                        os.path.join(ROOT, "data/dedupe2/corpus.json"), str(STRIDE), jsn],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verify_estate: live mordred (float64) run failed")
    d = json.load(open(jsn))
    if d["cols"] != COLS:
        raise SystemExit("verify_estate: live mordred emitted %s, expected %s"
                         % (d["cols"], COLS))
    ref64 = np.array(d["vals"], dtype=np.float64)
    A, B = ours[::STRIDE], ours2[::STRIDE]
    print("\nfloat64 cross-check against a LIVE mordred, %d molecules (every %dth), %.1f s"
          % (len(ref64), STRIDE, time.time() - t0))
    print("  matrix.npz is float32 and rounds away ~29 bits; this asks the exactness question")
    print("  at the precision mordred answers it in.")
    print("  %-10s %7s %14s %14s %10s" %
          ("column", "finite", "exact as-is", "exact rdkit-ord", "max rel"))
    fail = False
    for j, c in enumerate(COLS):
        fin = ~np.isnan(ref64[:, j]) & ~np.isnan(A[:, j])
        nan_dis = int((np.isnan(ref64[:, j]) != np.isnan(A[:, j])).sum())
        ea = int((A[fin, j] == ref64[fin, j]).sum())
        eb = int((B[fin, j] == ref64[fin, j]).sum())
        rel = (np.abs(A[fin, j] - ref64[fin, j])
               / np.maximum(np.abs(ref64[fin, j]), 1e-300)) if fin.any() else np.zeros(1)
        n = int(fin.sum())
        if ea != n or nan_dis:
            fail = True
        print("  %-10s %7d %14s %14s %10.2e"
              % (c, n, "%d" % ea if ea == n else "%d  <-" % ea,
                 "%d" % eb if eb == n else "%d  <-" % eb, rel.max()))
        if nan_dis:
            print("      NaN disagreements: %d" % nan_dis)
    if not keep:
        for p in (script, jsn):
            try:
                os.remove(p)
            except OSError:
                pass
    return fail


def main():
    keep = "--keep" in sys.argv
    corpus = json.load(open(os.path.join(ROOT, "data/dedupe2/corpus.json")))
    smiles = corpus["smiles"]
    strata = corpus["stratum"]

    z = np.load(os.path.join(ROOT, "data/dedupe2/matrix.npz"), allow_pickle=True)
    md = [str(x) for x in z["md_names"]]
    missing = [c for c in COLS if c not in md]
    if missing:
        raise SystemExit("verify_estate: data/dedupe2/matrix.npz has no reference column(s) %s "
                         "-- the ground-truth matrix and this group's column list disagree"
                         % missing)
    ref = np.column_stack([z["MD"][:, md.index(c)] for c in COLS])
    ncol_ref = {t: z["MD"][:, md.index("N" + t)] for t in EXT_TYPES if "N" + t in md}

    dumpf = os.path.join(BUILD, "estate_ext_in.txt")
    outf = os.path.join(BUILD, "estate_ext_cpp.txt")
    os.makedirs(BUILD, exist_ok=True)

    t0 = time.time()
    dump(smiles, dumpf)
    print("dumped %d molecules in %.1f s" % (len(smiles), time.time() - t0))

    exe = build_driver()
    t0 = time.time()
    r = subprocess.run([exe, dumpf, outf], capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verify_estate: driver failed")
    print("C++ pass over %d molecules in %.1f s" % (len(smiles), time.time() - t0))

    ours = np.loadtxt(outf, dtype=np.float64)
    if ours.shape != (len(smiles), len(COLS)):
        raise SystemExit("verify_estate: driver produced %s, expected (%d, %d)"
                         % (ours.shape, len(smiles), len(COLS)))

    report, worst = grade(ours, ref, smiles, strata)

    print()
    print("%-10s %7s %7s %7s %7s %9s %8s %8s" %
          ("column", "finite", "exact", "<=1e-9", "<=1e-6", "NaN both", "NaN dis", "mismatch"))
    print("-" * 74)
    allbad = 0
    for rr in report:
        allbad += rr["nmis"]
        print("%-10s %7d %7d %7d %7d %9d %8d %8d" %
              (rr["name"], rr["finite"], rr["exact"], rr["w9"], rr["w6"],
               rr["nan_both"], rr["nan_dis"], rr["nmis"]))
    print("-" * 74)
    print("total mismatched cells: %d of %d" % (allbad, len(smiles) * len(COLS)))

    if allbad:
        print("\nmismatches (up to 10 per column):")
        for rr in report:
            for i in worst[rr["name"]]:
                print("  %-10s %-60s ref=%-18.10g ours=%-18.10g"
                      % (rr["name"], smiles[i][:60], ref[i, COLS.index(rr["name"])],
                         ours[i, COLS.index(rr["name"])]))

    # ---- attribution: where do the disagreements live? ----------------------------------
    # The sixteen MAX/MIN columns are reductions over hume_blocks.h's estate_from(), so any
    # disagreement is either in this header's reduction or in the index it reduces. Re-running
    # with the index accumulated in RDKit's own order separates the two, and the answer is
    # reported rather than argued. See NOTES_estate.md.
    outf2 = os.path.join(BUILD, "estate_ext_cpp_rdkitorder.txt")
    r = subprocess.run([exe, dumpf, outf2, "rdkitorder"], capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verify_estate: rdkitorder driver failed")
    ours2 = np.loadtxt(outf2, dtype=np.float64)
    report2, _ = grade(ours2, ref, smiles, strata)
    bad2 = sum(rr["nmis"] for rr in report2)
    print("\nattribution (float32 reference): the same 22 reductions over an index accumulated")
    print("  in RDKit's order. rdkit/Chem/EState/EState.py does `res = accum + Is` at the END;")
    print("  hume_blocks.h's estate_from() seeds S[i] = I[i] and accumulates into it -- same")
    print("  terms, different association.")
    print("  exact cells   %d -> %d   of %d"
          % (sum(rr["exact"] for rr in report), sum(rr["exact"] for rr in report2),
             len(smiles) * len(COLS)))
    print("  mismatches    %d -> %d" % (allbad, bad2))

    # ---- the same question at mordred's own precision -----------------------------------
    f64_fail = float64_check(exe, dumpf, ours, ours2, keep)

    if not keep:
        try:
            os.remove(outf2)
        except OSError:
            pass

    # ---- the quirk, stated as a check rather than a claim -------------------------------
    print("\nMAX/MIN absent-type convention (mordred: NaN when N<t> == 0):")
    ok = True
    for t in EXT_TYPES:
        if t not in ncol_ref:
            continue
        absent = ncol_ref[t] == 0
        for pre in ("MAX", "MIN"):
            j = COLS.index(pre + t)
            ours_nan = np.isnan(ours[:, j])
            agree = int((ours_nan == absent).sum())
            if agree != len(smiles):
                ok = False
            print("  %-10s N%s==0 on %5d molecules; ours NaN on %5d; agree on %5d/%d"
                  % (pre + t, t, int(absent.sum()), int(ours_nan.sum()), agree, len(smiles)))
    print("  -> %s" % ("NaN <-> absent holds for all 16 columns" if ok else "DISAGREEMENT"))
    print("  (zeros produced by these 16 columns: %d -- the convention is NaN, never 0)"
          % int((ours[:, 1:17] == 0).sum()))

    # ---- timing --------------------------------------------------------------------------
    print("\ntiming: estate_ext::compute() alone, best of 5 per molecule")
    r = subprocess.run([exe, "bench", dumpf, "5"], capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verify_estate: bench failed")
    us = np.array([float(x) for x in r.stdout.split()])
    st = np.array(strata)
    print("  %-12s %7s %9s %9s %9s" % ("stratum", "n", "mean us", "sd", "p95"))
    for s in ["0-15", "15-25", "25-35", "35-55", "55-1000000"]:
        sel = us[st == s]
        if len(sel):
            print("  %-12s %7d %9.2f %9.2f %9.2f"
                  % (s, len(sel), sel.mean(), sel.std(), np.percentile(sel, 95)))
    print("  %-12s %7d %9.2f %9.2f %9.2f"
          % ("ALL", len(us), us.mean(), us.std(), np.percentile(us, 95)))

    if not keep:
        for p in (dumpf, outf):
            try:
                os.remove(p)
            except OSError:
                pass

    print()
    if allbad or f64_fail:
        print("NOT FULLY EXACT. See NOTES_estate.md -- the residual is hume_blocks.h's")
        print("estate_from() accumulation order, not this header's reductions; the")
        print("`exact rdkit-ord` column above is what the same 22 reductions score once the")
        print("per-atom index is accumulated the way RDKit accumulates it.")
    else:
        print("ALL 22 COLUMNS EXACT.")
    raise SystemExit(1 if (allbad or f64_fail) else 0)


if __name__ == "__main__":
    main()
