#!/usr/bin/env python
"""Verification harness for src/hume_core/counts_ext.h -- the 31 E_counts columns.

    .venv/bin/python verify_counts.py            dump the corpus, build, grade, bench
    .venv/bin/python verify_counts.py --n 2000   a subset, for a quick loop
    .venv/bin/python verify_counts.py --no-bench skip the timing pass

HOUSE RULE 1: NOT ONE DESCRIPTOR VALUE IS COMPUTED HERE. This file does exactly three things --
it serialises the boundary (the same fields src/hume/_extract.py serialises, from the same RDKit
calls), it shells out to a C++ driver built from counts_ext.h, and it compares that driver's
output with data/dedupe2/matrix.npz. Every number graded below was produced by C++.

WHY IT BUILDS ITS OWN DRIVER instead of importing `hume`. The contract forbids this agent from
touching src/hume_core/bindings.cpp, so counts_ext.h is not reachable from the extension yet.
The driver is written into build_counts/ (a build artefact directory, not repository source) and
compiled with the same `c++ -O3 -std=c++17` the other harnesses in cpp/ use, so the numbers are
produced by the same compiler and flags the shipped extension is built with.

WHAT IS GRADED. All 31 columns against mordred's values for all 20,000 corpus molecules, with
per-column exact / 1e-9 / 1e-6 / mismatch counts and NaN agreement, and every mismatch printed
with its SMILES. Two extra checks ride along:
  * counts_ext::driftGuard on every molecule -- ringPass over ringcount's own 49 specs must equal
    ringcount::compute cell for cell (see the note in counts_ext.h about the one duplicated pass).
  * the same driver run again over mordred's RAW ring set, so the ring divergence is a measured
    number and not a claim. --kekule adds the Kekule stability experiment of NOTES section 3.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build_counts"
COLS = json.load(open(ROOT / "results/dedupe2/agent_groups.json"))["E_counts"]

# ------------------------------------------------------------------------------------------------
# The C++ driver. Written out rather than committed: it is a test fixture for one header, and the
# only repository source this group adds is that header.
#
# The exchange format, one text file for the whole corpus:
#
#     NMOL
#     repeated NMOL times:
#       n nb nr nRot stratum
#       n  lines:  z deg nH fchg hyb arom ring cip nring tval mass      (atom_i cols 0-9 + mass)
#       nb lines:  u v conj inring bcode btype order                    (bond_i cols 0-5 + bond_d)
#       nr lines:  k a1 a2 ... ak                                       (the ring CSR, one ring)
#
# `order` and `mass` are the only floats and are written %.17g, which round-trips float64 exactly;
# everything else is an integer, so the file has no precision of its own.
# ------------------------------------------------------------------------------------------------
DRIVER = r"""
// Generated by verify_counts.py. Test fixture for src/hume_core/counts_ext.h.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "../src/hume_core/counts_ext.h"

struct Rec {
  int n = 0, nb = 0, nr = 0, nRot = 0, stratum = 0;
  std::vector<int32_t> arows;                 // n * 10
  std::vector<double> adbl;                   // n * 1 (mass)
  std::vector<int32_t> brows;                 // nb * 6
  std::vector<double> bord;                   // nb
  std::vector<int32_t> ring_off, ring_at;
};

static std::vector<Rec> load(const char *path) {
  FILE *f = std::fopen(path, "r");
  if (!f) { std::fprintf(stderr, "counts driver: cannot open %s\n", path); std::exit(2); }
  int nm = 0;
  if (std::fscanf(f, "%d", &nm) != 1) { std::fprintf(stderr, "bad header\n"); std::exit(2); }
  std::vector<Rec> out(nm);
  for (int k = 0; k < nm; ++k) {
    Rec &r = out[k];
    if (std::fscanf(f, "%d %d %d %d %d", &r.n, &r.nb, &r.nr, &r.nRot, &r.stratum) != 5) {
      std::fprintf(stderr, "counts driver: truncated at molecule %d\n", k); std::exit(2);
    }
    r.arows.assign((size_t)r.n * 10, 0);
    r.adbl.assign((size_t)r.n, 0.0);
    for (int i = 0; i < r.n; ++i) {
      int32_t *a = &r.arows[(size_t)i * 10];
      if (std::fscanf(f, "%d %d %d %d %d %d %d %d %d %d %lf", &a[0], &a[1], &a[2], &a[3], &a[4],
                      &a[5], &a[6], &a[7], &a[8], &a[9], &r.adbl[i]) != 11) {
        std::fprintf(stderr, "counts driver: bad atom %d of molecule %d\n", i, k); std::exit(2);
      }
    }
    r.brows.assign((size_t)r.nb * 6, 0);
    r.bord.assign((size_t)r.nb, 0.0);
    for (int e = 0; e < r.nb; ++e) {
      int32_t *b = &r.brows[(size_t)e * 6];
      if (std::fscanf(f, "%d %d %d %d %d %d %lf", &b[0], &b[1], &b[2], &b[3], &b[4], &b[5],
                      &r.bord[e]) != 7) {
        std::fprintf(stderr, "counts driver: bad bond %d of molecule %d\n", e, k); std::exit(2);
      }
    }
    r.ring_off.assign(1, 0);
    for (int q = 0; q < r.nr; ++q) {
      int len = 0;
      if (std::fscanf(f, "%d", &len) != 1) {
        std::fprintf(stderr, "counts driver: bad ring %d of molecule %d\n", q, k); std::exit(2);
      }
      for (int t = 0; t < len; ++t) {
        int a = 0;
        if (std::fscanf(f, "%d", &a) != 1) {
          std::fprintf(stderr, "counts driver: bad ring atom, molecule %d\n", k); std::exit(2);
        }
        r.ring_at.push_back(a);
      }
      r.ring_off.push_back((int32_t)r.ring_at.size());
    }
  }
  std::fclose(f);
  return out;
}

// Build the two molecule views bindings.cpp already builds, from the boundary rows.
static void fill(const Rec &r, constit::Mol &km, ringcount::Mol &rm) {
  km.build_from_rows(r.n, r.arows.data(), 10, r.adbl.data(), 1, r.nb, r.brows.data(), 6,
                     r.bord.data(), r.nr, r.ring_off.data(), r.ring_at.data());
  rm.alloc(r.n);
  for (int i = 0; i < r.n; ++i) {
    rm.z[i] = r.arows[(size_t)i * 10 + 0];
    rm.arom[i] = (uint8_t)r.arows[(size_t)i * 10 + 5];
  }
  for (int q = 0; q < r.nr; ++q)
    rm.add_ring(&r.ring_at[r.ring_off[q]], r.ring_off[q + 1] - r.ring_off[q]);
}

// nBondsD and nBondsKD are constit.h's own answer, called rather than reimplemented. bindings.cpp
// will read the same two values out of `out[OFF_CONSTIT + ...]` instead of calling again.
static void constit_bonds(const constit::Mol &km, int &nBondsD, int &nBondsKD) {
  const constit::HDerived H(km);
  double bc[6];
  constit::bondCount(km, H, bc);
  nBondsD = (int)bc[1];
  nBondsKD = (int)bc[5];
}

int main(int argc, char **argv) {
  try {
    counts_ext::selfCheck();
  } catch (const std::exception &e) {
    std::fprintf(stderr, "DRIFT GUARD FAILED: %s\n", e.what());
    return 3;
  }
  const char *cmd = argc > 1 ? argv[1] : "names";
  if (!std::strcmp(cmd, "names")) {
    for (int c = 0; c < counts_ext::N_COLS; ++c)
      std::printf("%s%s", counts_ext::col_name(c), c + 1 == counts_ext::N_COLS ? "\n" : " ");
    return 0;
  }
  const char *path = argc > 2 ? argv[2] : "build_counts/counts_mols.txt";
  std::vector<Rec> recs = load(path);
  constit::Mol km;
  ringcount::Mol rm;
  ringcount::Scratch S;
  double out[counts_ext::N_COLS];

  if (!std::strcmp(cmd, "dump")) {
    FILE *f = std::fopen(argc > 3 ? argv[3] : "build_counts/counts_values.txt", "w");
    if (!f) { std::fprintf(stderr, "counts driver: cannot write output\n"); return 2; }
    for (size_t k = 0; k < recs.size(); ++k) {
      const Rec &r = recs[k];
      try {
        fill(r, km, rm);
        counts_ext::driftGuard(rm, S, "corpus molecule");
        counts_ext::Inputs in;
        in.nRot = r.nRot;
        constit_bonds(km, in.nBondsD, in.nBondsKD);
        counts_ext::compute(km, rm, in, out, S);
      } catch (const std::exception &e) {
        std::fprintf(stderr, "counts driver: molecule index %zu threw: %s\n", k, e.what());
        return 4;
      }
      for (int c = 0; c < counts_ext::N_COLS; ++c)
        std::fprintf(f, c ? " %.17g" : "%.17g", out[c]);
      std::fputc('\n', f);
    }
    std::fclose(f);
    std::printf("counts_ext: wrote %zu molecules x %d columns\n", recs.size(),
                counts_ext::N_COLS);
    return 0;
  }

  if (!std::strcmp(cmd, "bench")) {
    // CONTENDED -- other agents build in this checkout concurrently, so these are upper bounds.
    // Molecule construction is INSIDE the timed region because the caller pays it too; the file
    // parse is not. Every column is summed into `sink` so -O3 cannot delete the work.
    //
    // THREE NUMBERS, because only one of them is what bindings.cpp will actually pay:
    //   mode 0  compute() alone                -- THE MARGINAL COST. `W.km` and `W.rm` already
    //                                             exist in bindings.cpp's Work, and nBondsD /
    //                                             nBondsKD are read out of `out`.
    //   mode 1  + constit::bondCount           -- what it would cost if the two constit columns
    //                                             were recomputed instead of wired.
    //   mode 2  + building both molecule views -- the whole standalone path, an upper bound.
    int nstr = 0;
    for (const auto &r : recs) nstr = std::max(nstr, r.stratum + 1);
    const int REPS = 11;
    std::vector<int> cnt(nstr, 0);
    for (const auto &r : recs) cnt[r.stratum]++;
    double sink = 0;
    // Pre-build every molecule's views once for mode 0/1, so the timed region holds nothing else.
    std::vector<constit::Mol> KM(recs.size());
    std::vector<ringcount::Mol> RM(recs.size());
    std::vector<counts_ext::Inputs> IN(recs.size());
    for (size_t k = 0; k < recs.size(); ++k) {
      fill(recs[k], KM[k], RM[k]);
      IN[k].nRot = recs[k].nRot;
      constit_bonds(KM[k], IN[k].nBondsD, IN[k].nBondsKD);
    }
    for (int mode = 0; mode < 3; ++mode) {
      std::vector<std::vector<double>> per(nstr);        // us/mol per rep, per stratum
      for (int rep = 0; rep < REPS; ++rep) {
        std::vector<double> acc(nstr, 0.0);
        for (size_t k = 0; k < recs.size(); ++k) {
          const Rec &r = recs[k];
          auto t0 = std::chrono::steady_clock::now();
          if (mode == 2) {
            fill(r, km, rm);
            counts_ext::Inputs in;
            in.nRot = r.nRot;
            constit_bonds(km, in.nBondsD, in.nBondsKD);
            counts_ext::compute(km, rm, in, out, S);
          } else if (mode == 1) {
            counts_ext::Inputs in;
            in.nRot = r.nRot;
            constit_bonds(KM[k], in.nBondsD, in.nBondsKD);
            counts_ext::compute(KM[k], RM[k], in, out, S);
          } else {
            counts_ext::compute(KM[k], RM[k], IN[k], out, S);
          }
          auto t1 = std::chrono::steady_clock::now();
          acc[r.stratum] += std::chrono::duration<double, std::micro>(t1 - t0).count();
          for (int c = 0; c < counts_ext::N_COLS; ++c) sink += out[c];
        }
        for (int s = 0; s < nstr; ++s)
          if (cnt[s]) per[s].push_back(acc[s] / cnt[s]);
      }
      for (int s = 0; s < nstr; ++s) {
        if (!cnt[s]) continue;
        std::vector<double> v = per[s];
        double mean = 0;
        for (double x : v) mean += x;
        mean /= v.size();
        double sd = 0;
        for (double x : v) sd += (x - mean) * (x - mean);
        sd = std::sqrt(sd / (v.size() - 1));
        std::sort(v.begin(), v.end());
        std::printf("MODE %d STRATUM %d n=%d median %.3f mean %.3f sd %.3f min %.3f\n", mode, s,
                    cnt[s], v[v.size() / 2], mean, sd, v.front());
      }
    }
    if (sink == 12345.6789) std::printf("");
    return 0;
  }
  std::fprintf(stderr, "usage: counts_driver [dump IN OUT | bench IN | names]\n");
  return 1;
}
"""


# ------------------------------------------------------------------------------------------------
# Boundary serialisation. Exactly the RDKit calls src/hume/_extract.py makes, and nothing else.
# ------------------------------------------------------------------------------------------------
def dump_mols(smis, strata, path: Path, nrot_ref, rings="repaired"):
    """`rings="repaired"` is the boundary's own `rings_for()` -- what HUME ships.
    `rings="raw"` is RDKit's `RingInfo().AtomRings()` verbatim, which is what mordred saw. The
    only difference between the two dumps is the ring CSR, so running the SAME driver over both
    isolates the ring set as the sole cause of any divergence -- and no descriptor value is ever
    computed on this side of the boundary."""
    from rdkit import Chem, RDLogger

    RDLogger.DisableLog("rdApp.*")
    from hume._rings import rings_for

    if rings not in ("repaired", "raw"):
        raise ValueError(rings)
    TYPE_BIT = {Chem.BondType.SINGLE: 1, Chem.BondType.DOUBLE: 2, Chem.BondType.TRIPLE: 4}
    CIP = "_CIPCode"
    strat_id = {s: i for i, s in enumerate(sorted(set(strata)))}
    out = [str(len(smis))]
    for idx, smi in enumerate(smis):
        m = Chem.MolFromSmiles(smi)
        if m is None:
            raise SystemExit(f"verify_counts: RDKit could not parse corpus molecule {idx}: {smi}")
        ats = list(m.GetAtoms())
        rs = rings_for(m) if rings == "repaired" else m.GetRingInfo().AtomRings()
        out.append(f"{len(ats)} {m.GetNumBonds()} {len(rs)} {int(nrot_ref[idx])} "
                   f"{strat_id[strata[idx]]}")
        ri = m.GetRingInfo()
        for a in ats:
            cip = 0
            if a.HasProp(CIP):
                cip = 1 if a.GetProp(CIP) == "R" else -1
            out.append(
                f"{a.GetAtomicNum()} {a.GetDegree()} {a.GetTotalNumHs()} {a.GetFormalCharge()} "
                f"{int(a.GetHybridization())} {int(a.GetIsAromatic())} {int(a.IsInRing())} {cip} "
                f"{ri.NumAtomRings(a.GetIdx())} {a.GetTotalValence()} {a.GetMass():.17g}")
        for b in m.GetBonds():
            bt = b.GetBondType()
            code = TYPE_BIT.get(bt, 0)
            if b.GetIsAromatic():
                code |= 8
            out.append(f"{b.GetBeginAtomIdx()} {b.GetEndAtomIdx()} {int(b.GetIsConjugated())} "
                       f"{int(b.IsInRing())} {code} {int(bt)} {b.GetBondTypeAsDouble():.17g}")
        for r in rs:
            out.append(str(len(r)) + " " + " ".join(str(i) for i in r))
    path.write_text("\n".join(out) + "\n")


# ------------------------------------------------------------------------------------------------
# THE KEKULE STABILITY EXPERIMENT that decided rule 4 for nBondsKS. Re-parses each aromatic
# molecule from many randomly re-ordered SMILES and asks whether RDKit's own kekulized SINGLE and
# DOUBLE counts move. This calls the REFERENCE (RDKit) for ground truth -- it does not implement
# a descriptor. --kekule to run it; it takes about a minute.
# ------------------------------------------------------------------------------------------------
def kekule_stability(smis, n_probe=650, n_try=40, seed=0):
    import random

    from rdkit import Chem, RDLogger

    RDLogger.DisableLog("rdApp.*")
    rng = random.Random(seed)

    def counts(m):
        mh = Chem.AddHs(m)
        Chem.Kekulize(mh)
        s = sum(1 for b in mh.GetBonds() if b.GetBondType() == Chem.BondType.SINGLE)
        d = sum(1 for b in mh.GetBonds() if b.GetBondType() == Chem.BondType.DOUBLE)
        return s, d

    cand = []
    for s in smis:
        m = Chem.MolFromSmiles(s)
        if m is not None and any(b.GetIsAromatic() for b in m.GetBonds()):
            cand.append(s)
    probe = rng.sample(cand, min(n_probe, len(cand)))
    moved_ks = moved_kd = reparses = 0
    examples = []
    for s in probe:
        m0 = Chem.MolFromSmiles(s)
        n = m0.GetNumAtoms()
        vks, vkd = set(), set()
        a, b = counts(m0)
        vks.add(a)
        vkd.add(b)
        for _ in range(n_try):
            perm = list(range(n))
            rng.shuffle(perm)
            m2 = Chem.MolFromSmiles(
                Chem.MolToSmiles(Chem.RenumberAtoms(m0, perm), canonical=False))
            if m2 is None:
                continue
            reparses += 1
            a, b = counts(m2)
            vks.add(a)
            vkd.add(b)
        if len(vks) > 1:
            moved_ks += 1
            if len(examples) < 5:
                examples.append((s, sorted(vks)))
        if len(vkd) > 1:
            moved_kd += 1
    return len(probe), len(cand), reparses, moved_ks, moved_kd, examples



def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=0, help="grade only the first N molecules")
    ap.add_argument("--no-bench", action="store_true")
    ap.add_argument("--no-rebuild", action="store_true")
    ap.add_argument("--kekule", action="store_true",
                    help="re-run the Kekule stability experiment behind NOTES_counts.md section 3")
    args = ap.parse_args()

    BUILD.mkdir(exist_ok=True)
    src = BUILD / "counts_driver.cpp"
    exe = BUILD / "counts_driver"
    src.write_text(DRIVER)
    if not args.no_rebuild or not exe.exists():
        cc = os.environ.get("CXX", "c++")
        cmd = [cc, "-O3", "-std=c++17", "-o", str(exe), str(src)]
        print("build:", " ".join(cmd))
        t0 = time.time()
        r = subprocess.run(cmd, cwd=ROOT)
        if r.returncode:
            raise SystemExit("verify_counts: the driver did not compile")
        print(f"  compiled in {time.time() - t0:.1f}s")

    names = subprocess.run([str(exe), "names"], cwd=ROOT, capture_output=True,
                           text=True, check=True).stdout.split()
    if names != COLS:
        raise SystemExit("verify_counts: counts_ext::col_name order does not match "
                         f"agent_groups.json E_counts\n  header: {names}\n  groups: {COLS}")
    print(f"columns: {len(names)} names, in agent_groups E_counts order  OK")

    d = np.load(ROOT / "data/dedupe2/matrix.npz", allow_pickle=True)
    md_names = list(d["md_names"])
    md_index = {n: i for i, n in enumerate(md_names)}
    MD = d["MD"]
    corpus = json.load(open(ROOT / "data/dedupe2/corpus.json"))
    smis, strata = corpus["smiles"], corpus["stratum"]
    N = args.n if args.n else len(smis)
    smis, strata = smis[:N], strata[:N]
    MD = MD[:N]
    print(f"corpus: {N:,} molecules, strata {sorted(set(strata))}")

    nrot_ref = MD[:, md_index["nRot"]]

    def run(rings, tag):
        """Serialise the boundary with `rings`, run the driver, return its (N, 31) values."""
        t0 = time.time()
        mols = BUILD / f"counts_mols_{tag}.txt"
        vals = BUILD / f"counts_values_{tag}.txt"
        dump_mols(smis, strata, mols, nrot_ref, rings=rings)
        print(f"boundary dumped ({rings} rings) in {time.time() - t0:.1f}s -> {mols}")
        if subprocess.run([str(exe), "dump", str(mols), str(vals)], cwd=ROOT).returncode:
            raise SystemExit("verify_counts: the driver failed (see message above)")
        A = np.loadtxt(vals, dtype=np.float64)
        if A.ndim == 1:
            A = A.reshape(1, -1)
        if A.shape != (N, len(COLS)):
            raise SystemExit(f"verify_counts: driver produced {A.shape}, "
                             f"expected {(N, len(COLS))}")
        return mols, A

    mols_txt, X = run("repaired", "repaired")

    # ---- grading -------------------------------------------------------------------------------
    print()
    print(f"{'column':13s} {'exact':>7s} {'1e-9':>6s} {'1e-6':>6s} {'MISMATCH':>9s} "
          f"{'nan-agree':>10s} {'nan-disagree':>13s}")
    total_bad = 0
    bad_detail = []
    for c, name in enumerate(COLS):
        ref = MD[:, md_index[name]].astype(np.float64)
        ours = X[:, c]
        rn, on = np.isnan(ref), np.isnan(ours)
        nan_agree = int((rn & on).sum())
        nan_dis = int((rn ^ on).sum())
        both = ~rn & ~on
        exact = int((ref[both] == ours[both]).sum())
        den = np.where(ref[both] != 0, np.abs(ref[both]), 1.0)
        rel = np.abs(ref[both] - ours[both]) / den
        w9 = int(((rel <= 1e-9) & (ref[both] != ours[both])).sum())
        w6 = int(((rel <= 1e-6) & (rel > 1e-9)).sum())
        bad = int(((rel > 1e-6)).sum()) + nan_dis
        total_bad += bad
        print(f"{name:13s} {exact:7d} {w9:6d} {w6:6d} {bad:9d} {nan_agree:10d} {nan_dis:13d}")
        if bad:
            idx = np.where(both)[0][rel > 1e-6]
            for i in list(idx) + list(np.where(rn ^ on)[0]):
                bad_detail.append((name, smis[i], float(ref[i]), float(ours[i])))

    print()
    if bad_detail:
        print(f"MISMATCHES ({len(bad_detail)}):")
        for name, smi, ref, ours in bad_detail[:200]:
            print(f"  {name:13s} ref={ref!r:>12} ours={ours!r:>12}  {smi}")
        if len(bad_detail) > 200:
            print(f"  ... and {len(bad_detail) - 200} more")
    print(f"TOTAL: {total_bad} mismatched cells out of {N * len(COLS):,} "
          f"({N:,} molecules x {len(COLS)} columns)")
    print("counts_ext::driftGuard passed on every molecule "
          f"({N * 49:,} ringPass-vs-ringcount::compute cells)")

    # ---- the ring divergence, measured by RUNNING THE SAME C++ TWICE ----------------------------
    # The only difference between the two dumps is the ring CSR -- repaired (`rings_for`, what
    # HUME ships) versus raw (`RingInfo().AtomRings()`, what mordred saw). So this isolates the
    # ring set as the sole cause of any divergence, without a line of descriptor logic in python.
    print()
    print("RING SET: mordred's raw Chem.GetSymmSSSR vs the boundary's repaired set")
    _, XR = run("raw", "raw")
    moved = set()
    for c, name in enumerate(COLS):
        ref = MD[:, md_index[name]].astype(np.float64)
        braw = int((XR[:, c] != ref).sum())
        brep = int((X[:, c] != ref).sum())
        if braw or brep:
            print(f"  {name:13s} raw-vs-mordred {braw:5d}   repaired-vs-mordred {brep:5d}")
        moved |= set(np.where(X[:, c] != XR[:, c])[0].tolist())
    print(f"  columns where the RAW ring set reproduces mordred exactly: "
          f"{sum(1 for c, n in enumerate(COLS) if (XR[:, c] == MD[:, md_index[n]]).all())}"
          f" of {len(COLS)}")
    print(f"  molecules where the two ring sets give different values: {len(moved)} of {N:,}")
    for i in sorted(moved)[:10]:
        d = [(n, float(XR[i, c]), float(X[i, c])) for c, n in enumerate(COLS)
             if XR[i, c] != X[i, c]]
        print(f"    {d}  {smis[i]}")

    # ---- the Kekule stability experiment behind NOTES_counts.md section 3 -----------------------
    if args.kekule:
        print()
        print("KEKULE STABILITY: is nBondsKS ill-posed? (contract rule 4)")
        npr, ncand, nrep, mks, mkd, ex = kekule_stability(smis)
        print(f"  {npr} aromatic molecules sampled from {ncand}, 40 random SMILES orderings each "
              f"({nrep} re-parses)")
        print(f"  RDKit's own kekulized SINGLE count moved on {mks} of {npr} molecules")
        print(f"  RDKit's own kekulized DOUBLE count moved on {mkd} of {npr} molecules")
        for e in ex:
            print(f"    {e}")
        print("  0 and 0 means the column is WELL-POSED and rule 4 says reproduce it.")

    # ---- timing --------------------------------------------------------------------------------
    if not args.no_bench:
        print()
        strat_names = sorted(set(strata))
        out = subprocess.run([str(exe), "bench", str(mols_txt)], cwd=ROOT,
                             capture_output=True, text=True, check=True).stdout
        MODE = {0: "counts_ext::compute alone -- THE MARGINAL COST in bindings.cpp",
                1: "+ constit::bondCount (if nBondsD/nBondsKD were recomputed, not wired)",
                2: "+ building constit::Mol and ringcount::Mol (standalone upper bound)"}
        print("TIMING (11 reps, file parse excluded; CONTENDED -- other agents build here too)")
        for mode in (0, 1, 2):
            print(f"  mode {mode}: {MODE[mode]}")
            tot_n, tot_us = 0, 0.0
            for line in out.strip().splitlines():
                f = line.split()
                if int(f[1]) != mode:
                    continue
                s, n, med, mean, sd = int(f[3]), int(f[4].split("=")[1]), float(f[6]), \
                    float(f[8]), float(f[10])
                print(f"    stratum {strat_names[s]:>10s}  n={n:5d}  median {med:7.3f} us/mol  "
                      f"mean {mean:7.3f}  sd {sd:6.3f}")
                tot_n += n
                tot_us += mean * n
            print(f"    ALL                    n={tot_n:5d}  mean   {tot_us / tot_n:7.3f} us/mol"
                  f"   ({100 * (tot_us / tot_n) / 830:.2f}% of HUME's ~830 us/mol budget)")

    return 1 if total_bad else 0


if __name__ == "__main__":
    sys.exit(main())
