// GENERATED by cpp/gen_constit_tables.py -- do not edit.
//
// The numeric specification of the small constitutional families in
// src/hume_core/constit.h: mordred's 1994 atomic polarizabilities, the thirteen Bondi
// volume contributions VdwVolumeABC is defined over, the two mass tables CalcExactMolWt
// and _CalcMolWt read, and the sixteen Filter-it LogS coefficients IN THEIR SUMMATION
// ORDER.
//
// PROVENANCE.  `spec` is sha256 over the IEEE-754 bit patterns of every number below, in
// the canonical rendering cpp/gen_constit_tables.py:canonical() defines and
// src/hume_core/constit.h:specString() reproduces.  constit.h RECOMPUTES it on first use
// and throws if it disagrees, so hand-editing a number here is caught in C++ with no
// rdkit and no mordred in the process.  The `file` hashes are INFORMATIONAL only.
//
// Regenerate UNDER THE PIN.  mordred 1.2.0 needs python 3.11 (distutils) and numpy 1.x;
// asking for mordred alongside numpy 2 does not error, it silently resolves mordred DOWN
// to 0.6.0, which is a different library:
//     uv run --isolated --no-project --python 3.11 --with "mordred==1.2.0" \
//            --with "rdkit==2025.9.2" --with "numpy==1.26.4" \
//            python cpp/gen_constit_tables.py
//
//   mordred 1.2.0   (pin: 1.2.0)
//   rdkit   2025.09.2   (pin: 2025.9.2)
//   numpy   1.26.4
//   python  3.11.15
//   spec    sha256(numbers) = f2f4b8c9fa00565d23f11f565d6ecc85d20724628640a7b2445f3a202d74fa11
//   file    sha256(mordred/LogS.py) = f2502f1c9bd22338e5390752ed5dce8746fa2a985f6750819817fa2886ca5750   (informational)
//   file    sha256(mordred/VdwVolumeABC.py) = 59506f8312c760444f9e00bf0e075a8f63476d92299295c20d4f5f294f0d3d51   (informational)
//   file    sha256(mordred/_atomic_property.py) = 6dd68f20042f5bc3a2a7a8ab88e96bdf6b63445b8a7d83e79ffa0928cca9aad7   (informational)

#ifndef HUME_CONSTIT_TABLES_H
#define HUME_CONSTIT_TABLES_H

#include <limits>

namespace constit_tbl {

constexpr char SPEC_SHA256[] = "f2f4b8c9fa00565d23f11f565d6ecc85d20724628640a7b2445f3a202d74fa11";
constexpr int MAX_Z = 118;

// mordred._atomic_property.polarizability94, i.e. mordred/data/polarizalibity94.txt
// (Handbook of Chemistry and Physics, 94th edition).  Index is the atomic number; an
// element mordred's table does not cover is 0.0 here, which is NOT a legal input -- a
// KeyError in mordred is a hard failure and constit.h reports one rather than summing 0.
constexpr double POL94[MAX_Z + 1] = {
    std::numeric_limits<double>::quiet_NaN(), 0.666793, 0.2050522, 24.33, 5.6, 3.03,
    1.67, 1.1, 0.802, 0.557, 0.39432, 24.11,
    10.6, 6.8, 5.53, 3.63, 2.9, 2.18,
    1.6411, 43.06, 22.8, 17.8, 14.6, 12.4,
    11.6, 9.4, 8.4, 7.5, 6.8, 6.2,
    5.75, 8.12, 5.84, 4.31, 3.77, 3.05,
    2.4844, 47.24, 23.5, 22.7, 17.9, 15.7,
    12.8, 11.4, 9.6, 8.6, 4.8, 6.78,
    7.36, 10.2, 7.84, 6.6, 5.5, 5.35,
    4.044, 59.42, 39.7, 31.1, 29.6, 28.2,
    31.4, 30.1, 28.8, 27.7, 23.5, 25.5,
    24.5, 23.6, 22.7, 21.8, 20.9, 21.9,
    16.2, 13.1, 11.1, 9.7, 8.5, 7.6,
    6.5, 5.8, 5.02, 7.6, 7.01, 7.4,
    6.8, 6.0, 5.3, 48.6, 38.3, 32.1,
    32.1, 25.4, 24.9, 24.8, 24.5, 23.3,
    23.0, 22.7, 20.5, 19.7, 23.8, 18.2,
    16.4, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(),
    std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 4.06, std::numeric_limits<double>::quiet_NaN(),
    4.59, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(),
};

// mordred/VdwVolumeABC.py atom_contrib = 4/3 pi r^3 over its thirteen-element
// `bondi_radii` dict.  BONDI_OK is the DICT MEMBERSHIP, and it is load-bearing: Vabc is
// NaN for a molecule containing any element outside the thirteen, and a 0.0 contribution
// would silently be a number instead.
constexpr double BONDI[MAX_Z + 1] = {
    0.0, 7.238229473870882, 0.0, 0.0,
    0.0, 40.47878045660315, 20.579526276115534, 15.598531123848922,
    14.710226951490485, 13.30578842767868, 0.0, 0.0,
    0.0, 0.0, 38.79238608652677, 24.429024474314232,
    24.429024474314232, 22.44929750377706, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 26.521848780380633, 28.730912014629848, 26.521848780380633,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0,
};
constexpr int BONDI_OK[MAX_Z + 1] = {
    0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

// PeriodicTable::getMostCommonIsotopeMass(z) -- CalcExactMolWt's per-element mass for an
// atom with no explicit isotope.
constexpr double MONOISO[MAX_Z + 1] = {
    0.0, 1.007825032, 4.002603254, 7.01600455,
    9.0121822, 11.0093054, 12.0, 14.003074,
    15.99491462, 18.99840322, 19.99244018, 22.98976928,
    23.9850417, 26.98153863, 27.97692653, 30.97376163,
    31.972071, 34.96885268, 39.96238312, 38.96370668,
    39.96259098, 44.9559119, 47.9479463, 50.9439595,
    51.9405075, 54.9380451, 55.9349375, 58.933195,
    57.9353429, 62.9295975, 63.9291422, 68.9255736,
    73.9211778, 74.9215965, 79.9165213, 78.9183371,
    83.911507, 84.91178974, 87.9056121, 88.9058483,
    89.9047044, 92.9063781, 97.9054082, 96.906365,
    101.9043493, 102.905504, 105.903486, 106.905097,
    113.9033585, 114.903878, 119.9021947, 120.9038157,
    129.9062244, 126.904473, 131.9041535, 132.9054519,
    137.9052472, 138.9063533, 139.9054387, 140.9076528,
    141.9077233, 144.912749, 151.9197324, 152.9212303,
    157.9241039, 158.9253468, 163.9291748, 164.9303221,
    165.9302931, 168.9342133, 173.9388621, 174.9407718,
    179.94655, 180.9479958, 183.9509312, 186.9557531,
    191.9614807, 192.9629264, 194.9647911, 196.9665687,
    201.970643, 204.9744275, 207.9766521, 208.9803987,
    208.9824304, 209.987148, 222.0175706, 223.0197359,
    226.0254026, 227.0277521, 232.0380553, 231.035884,
    238.0507882, 236.04657, 238.0495599, 241.0568291,
    243.0613891, 247.070307, 249.0748535, 252.08298,
    257.095105, 258.098431, 259.10103, 262.10963,
    267.12153, 268.12545, 271.13347, 270.13362,
    269.13406, 278.15481, 281.16206, 281.16537,
    285.17411, 284.17873, 289.19042, 288.19274,
    293.20449, 292.20746, 294.21392,
};

// PeriodicTable::getAtomicWeight(z) -- _CalcMolWt's per-element mass, and the reference
// constit.h compares the boundary's `mass` column against to detect an isotope label
// without an isotope column at the boundary.
constexpr double AWEIGHT[MAX_Z + 1] = {
    0.0, 1.008, 4.003, 6.941,
    9.012, 10.812, 12.011, 14.007,
    15.999, 18.998, 20.18, 22.99,
    24.305, 26.982, 28.086, 30.974,
    32.067, 35.453, 39.948, 39.098,
    40.078, 44.956, 47.867, 50.944,
    51.996, 54.938, 55.845, 58.933,
    58.693, 63.546, 65.39, 69.723,
    72.61, 74.922, 78.96, 79.904,
    83.8, 85.468, 87.62, 88.906,
    91.224, 92.906, 95.94, 98.0,
    101.07, 102.906, 106.42, 107.868,
    112.412, 114.818, 118.711, 121.76,
    127.6, 126.904, 131.29, 132.905,
    137.328, 138.906, 140.116, 140.908,
    144.24, 145.0, 150.36, 151.964,
    157.25, 158.925, 162.5, 164.93,
    167.26, 168.934, 173.04, 174.967,
    178.49, 180.948, 183.84, 186.207,
    190.23, 192.217, 195.078, 196.967,
    200.59, 204.383, 207.2, 208.98,
    209.0, 210.0, 222.0, 223.0,
    226.0, 227.0, 232.038, 231.036,
    238.029, 237.0, 244.0, 243.0,
    247.0, 247.0, 251.0, 252.0,
    257.0, 258.0, 259.0, 262.0,
    267.0, 268.0, 269.0, 270.0,
    269.0, 278.0, 281.0, 281.0,
    285.0, 284.0, 289.0, 288.0,
    293.0, 292.0, 294.0,
};

// One electron mass per unit of formal charge, subtracted INSIDE CalcExactMolWt's atom
// loop.  Recovered from the running rdkit, not quoted: see the generator's docstring.
constexpr double ELECTRON_MASS = 0.00054857991;

// mordred/LogS.py: logS = 0.89823 - 0.10369*sqrt(MW), then one `+= count * coef` per
// pattern IN DICT INSERTION ORDER.  The order is spec, not presentation.
constexpr double LOGS_A = 0.89823;
constexpr double LOGS_B = -0.10369;
constexpr int N_LOGS = 16;
constexpr double LOGS_COEF[N_LOGS] = {
    0.71535, 0.41056, 0.82535, 0.31464,
    0.14787, 0.62998, -0.35634, -0.33888,
    -0.21912, -0.23057, -0.3757, -0.22435,
    -0.21728, -0.49721, -0.57982, -0.51547,
};
// The patterns the coefficients belong to, in the same order.  constit.h implements each
// as a predicate rather than running a matcher; these strings are here so the two can be
// read side by side, and cpp/verify_constit.py checks the predicates against rdkit's own
// SMARTS matcher pattern by pattern.
constexpr const char* LOGS_SMARTS[N_LOGS] = {
    "[NH0;X3;v3]",
    "[NH2;X3;v3]",
    "[nH0;X3]",
    "[OH0;X2;v2]",
    "[OH0;X1;v2]",
    "[OH1;X2;v2]",
    "[CH2;!R]",
    "[CH3;!R]",
    "[CH0;R]",
    "[CH2;R]",
    "[ch0]",
    "[ch1]",
    "F",
    "Cl",
    "Br",
    "I",
};

}  // namespace constit_tbl

#endif  // HUME_CONSTIT_TABLES_H
