// Wildman-Crippen atom typing, compiled.
//
// RDKit computes the per-atom (logP, MR) contribution pair by running 110 SMARTS patterns over
// the whole molecule in priority order and giving each atom the FIRST pattern it matches. That
// costs 79.3 us/mol COLD -- the second largest item in the HUME pipeline. It is a generic
// subgraph search being used to answer a question that, for 97 of the 110 rows, is a property of
// an atom and its immediate neighbours.
//
// This file replaces the search with straight-line code. The shape follows the measurement in
// cpp/spec_crippen.py rather than the other way round:
//
//   * 96 rows never look past the first shell. Each becomes a predicate over (element,
//     aromaticity, charge, H count, total degree) plus an injective assignment of at most four
//     branch atoms to neighbours.
//   * 14 rows reach two or three bonds, and every one of them is "one hop to a hinge atom, then
//     look at THAT atom's other substituents": the hydroxyl/enol hydrogens (H2/H3/H4) hinge on an
//     aliphatic O, and the carbonyl/carboxylate oxygens (O9/O10/O11/O12) hinge on an aliphatic C.
//     Both hinges are a one-line trigger. They are hand-written, with the grandparent explicitly
//     excluded so the query atoms stay distinct the way SMARTS requires.
//   * Dispatch is on (element, aromatic) first, because every row's first atom constrains the
//     element. An atom only ever walks the rows that could possibly claim it -- 26 for aliphatic
//     carbon, 14 for aromatic carbon, 1 for phosphorus, 0 for xenon.
//
// The numbers come from cpp/crippen_tables.h, generated by cpp/export_crippen.py from RDKit's own
// Data/Crippen.txt. Nothing here is hand-typed. Each predicate is stored NEXT TO the SMARTS string
// it implements and selfCheck() asserts at startup that the string still matches the generated
// table, so a future RDKit that reorders or edits a row fails loudly instead of drifting.
//
// SMARTS semantics this depends on, each verified against RDKit rather than assumed:
//   H  -> getTotalNumHs(true)   counts neighbouring explicit H ATOMS  (see `sh` below)
//   X  -> getTotalDegree()      == degree + getTotalNumHs(false)      (see `tx` below)
//   -  -> bond ORDER is single;  :  -> bond FLAG is aromatic;  default bond -> either
//   !C -> NOT aliphatic carbon; an aromatic c satisfies [!C]
//   +  -> charge exactly +1 (not "any positive"); -2 / -- -> exactly -2
//   an atom matching no row keeps (0.0, 0.0)
//
//   clang++ -O3 -std=c++17 -o cpp/crippen cpp/crippen.cpp
//   ./cpp/crippen verify        # per-atom vs RDKit, per-class breakdown
//   ./cpp/crippen paranoid      # dispatched path vs undispatched all-110-in-order path
//   ./cpp/crippen bench

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <string>
#include <vector>
#include <algorithm>
#include <chrono>

#include "crippen_tables.h"

// ---------------------------------------------------------------------------------------------
// molecule
// ---------------------------------------------------------------------------------------------

// Bond code bits. Order and the aromatic FLAG are separate on purpose: `-` asks about the order,
// `:` asks about the flag. Collapsing them answers the wrong question for the single bond joining
// two aromatic rings in biphenyl, which is the whole C20-vs-C19 distinction.
enum : uint8_t { B_SINGLE = 1, B_DOUBLE = 2, B_TRIPLE = 4, B_AROM = 8 };
enum : uint8_t { BM_ANY = B_SINGLE | B_AROM };   // the SMARTS default bond

struct Mol {
  int n = 0;
  std::vector<uint8_t>  z, arom, sh, tx, deg;    // sh = SMARTS H count, tx = SMARTS X
  std::vector<int8_t>   chg;
  std::vector<int32_t>  start;                   // CSR, size n+1
  std::vector<int32_t>  nbr;
  std::vector<uint8_t>  bcode;
  std::vector<double>   ref_logp, ref_mr;        // RDKit's answer, for verification only
  std::vector<uint8_t>  ref_row;                 // ... and the row it came from (255 = none)
};

// ---------------------------------------------------------------------------------------------
// atom primitives
// ---------------------------------------------------------------------------------------------

#define A_(name) static inline bool name(const Mol& m, int i)

A_(q_any)      { (void)m; (void)i; return true; }
A_(q_aro)      { return m.arom[i]; }                                   // a
A_(q_heavy)    { return m.z[i] != 1; }                                 // [!#1;A,a]
A_(q_aliHeavy) { return !m.arom[i] && m.z[i] != 1; }                   // [A;!#1]
A_(q_aroHeavy) { return m.arom[i] && m.z[i] != 1; }                    // [a;!#1]
A_(q_aliC)     { return m.z[i] == 6 && !m.arom[i]; }                   // C
A_(q_aroC)     { return m.z[i] == 6 && m.arom[i]; }                    // c
A_(q_anyC)     { return m.z[i] == 6; }                                 // [#6] / [C,c]
A_(q_aliN)     { return m.z[i] == 7 && !m.arom[i]; }                   // N
A_(q_anyN)     { return m.z[i] == 7; }                                 // [#7]
A_(q_aliO)     { return m.z[i] == 8 && !m.arom[i]; }                   // O
A_(q_aliS)     { return m.z[i] == 16 && !m.arom[i]; }                  // S
A_(q_F)        { return m.z[i] == 9  && !m.arom[i]; }
A_(q_Cl)       { return m.z[i] == 17 && !m.arom[i]; }
A_(q_Br)       { return m.z[i] == 35 && !m.arom[i]; }
A_(q_I)        { return m.z[i] == 53 && !m.arom[i]; }
A_(q_z9)       { return m.z[i] == 9;  }
A_(q_z17)      { return m.z[i] == 17; }
A_(q_z35)      { return m.z[i] == 35; }
A_(q_z53)      { return m.z[i] == 53; }
A_(q_z16)      { return m.z[i] == 16; }

// [N,O,P,S,F,Cl,Br,I] as used by C3/C4 -- every member is an ALIPHATIC element symbol.
A_(q_C3het) {
  if (m.arom[i]) return false;
  switch (m.z[i]) { case 7: case 8: case 15: case 16: case 9: case 17: case 35: case 53:
                    return true; default: return false; }
}
// [!C;A;!#1] in C5 -- aliphatic, not hydrogen, and not aliphatic carbon (so simply not carbon,
// given the aliphatic constraint).
A_(q_aliHeavyNotC) { return !m.arom[i] && m.z[i] != 1 && m.z[i] != 6; }
// [A;!C;!N;!O;!S;!F;!Cl;!Br;!I;!#1] in C13. Note P is NOT excluded here -- an aromatic carbon
// bonded to phosphorus IS a C13. C27's exclusion list, one row later, DOES contain P.
A_(q_C13nbr) {
  if (m.arom[i]) return false;
  switch (m.z[i]) { case 1: case 6: case 7: case 8: case 16: case 9: case 17: case 35: case 53:
                    return false; default: return true; }
}
// [A;!C;!N;!O;!P;!S;!F;!Cl;!Br;!I;!#1] in C27.
A_(q_C27nbr) {
  if (m.arom[i]) return false;
  switch (m.z[i]) { case 1: case 6: case 7: case 8: case 15: case 16: case 9: case 17: case 35:
                    case 53: return false; default: return true; }
}
A_(q_z7or8)  { return m.z[i] == 7 || m.z[i] == 8; }                                // [#7,#8]
A_(q_C25nbr) { return !m.arom[i] && (m.z[i] == 6 || m.z[i] == 7 || m.z[i] == 8); }  // [C,N,O]
A_(q_aliNorO){ return !m.arom[i] && (m.z[i] == 7 || m.z[i] == 8); }                 // [N,O]
A_(q_aliOorS){ return !m.arom[i] && (m.z[i] == 8 || m.z[i] == 16); }                // [O,S]
A_(q_S2nbr)  { return !m.arom[i] && (m.z[i]==7 || m.z[i]==8 || m.z[i]==15 || m.z[i]==16); }
A_(q_H1nbr)  { return m.z[i] == 6 || m.z[i] == 1; }                                 // [#6,#1]
A_(q_notHC)  { return m.z[i] != 1 && m.z[i] != 6; }                                 // [!#1;!#6]
A_(q_H4dbl)  { // [#6,#7,O,S] -- the first two are element-only, the last two aliphatic
  if (m.z[i] == 6 || m.z[i] == 7) return true;
  return !m.arom[i] && (m.z[i] == 8 || m.z[i] == 16);
}
// [!#6;!#7;!#8;!#16] and [!#6;!#7;!#8] -- ELEMENT negation, so an aromatic n/o/s is excluded too.
// Data/Crippen.txt still shows the aliphatic-symbol forms [!C;!N;!O;!S] / [!C;!N;!O] here, which
// WOULD admit aromatic n. The compiled C++ table does not, and the compiled table is what
// _CalcCrippenContribs runs. See CPP_OVERRIDES in export_crippen.py.
A_(q_notCNOS){ switch (m.z[i]) { case 6: case 7: case 8: case 16: return false;
                                 default: return true; } }
A_(q_notCNO) { switch (m.z[i]) { case 6: case 7: case 8: return false;
                                 default: return true; } }
A_(q_O7nbr)  { // [!#1;!N;!S]
  if (m.z[i] == 1) return false;
  if (m.arom[i]) return true;
  return m.z[i] != 7 && m.z[i] != 16;
}
A_(q_CX4orAroC) { return m.z[i] == 6 && (m.arom[i] ? true : m.tx[i] == 4); }        // [CX4,c]
A_(q_z16chg0)   { return m.z[i] == 16 && m.chg[i] == 0; }                          // [#16;-0]
A_(q_aliNneg)   { return !m.arom[i] && m.z[i] == 7 && m.chg[i] <= -1 && m.chg[i] >= -3; }

#undef A_

typedef bool (*AtomQ)(const Mol&, int);

// ---------------------------------------------------------------------------------------------
// branch assignment
//
// SMARTS maps distinct query atoms to DISTINCT molecule atoms, so a pattern like
// [CH1X4]([N,O,P,S,F,Cl,Br,I])([A;!#1])[A;!#1] is an injective assignment problem, not three
// independent existence tests. With at most four branches and a handful of neighbours the honest
// backtracking search is both correct and faster than anything cleverer.
// ---------------------------------------------------------------------------------------------

struct Br { uint8_t bm; AtomQ q; };

static bool assignRec(const Mol& m, int b0, int nb, const Br* br, int k, int slot, uint32_t used) {
  if (slot == k) return true;
  for (int j = 0; j < nb; ++j) {
    if ((used >> j) & 1u) continue;
    if (!(m.bcode[b0 + j] & br[slot].bm)) continue;
    if (!br[slot].q(m, m.nbr[b0 + j])) continue;
    if (assignRec(m, b0, nb, br, k, slot + 1, used | (1u << j))) return true;
  }
  return false;
}

// Branches of `c`, with `ex` (the atom we arrived from) already consumed. ex < 0 means "root".
static inline bool branches(const Mol& m, int c, int ex, const Br* br, int k) {
  int b0 = m.start[c], nb = m.start[c + 1] - b0;
  if (nb > 32) nb = 32;                 // no real molecule reaches this; the mask is 32 bits
  uint32_t used = 0;
  if (ex >= 0) {
    for (int j = 0; j < nb; ++j) if (m.nbr[b0 + j] == ex) { used = 1u << j; break; }
  }
  return assignRec(m, b0, nb, br, k, 0, used);
}

// "does root have a neighbour reached by a bond in `bm` satisfying `q`" -- the k==1 fast path.
static inline int findNbr(const Mol& m, int root, uint8_t bm, AtomQ q, int from = 0) {
  for (int e = m.start[root] + from; e < m.start[root + 1]; ++e)
    if ((m.bcode[e] & bm) && q(m, m.nbr[e])) return e;
  return -1;
}
static inline bool hasNbr(const Mol& m, int root, uint8_t bm, AtomQ q) {
  return findNbr(m, root, bm, q) >= 0;
}

#define B1(bm, q)                  static const Br _b[] = {{bm, q}};                 (void)_b
#define B2(a, b, c, d)             static const Br _b[] = {{a, b}, {c, d}};          (void)_b
#define B3(a, b, c, d, e, f)       static const Br _b[] = {{a, b}, {c, d}, {e, f}};  (void)_b
#define B4(a,b,c,d,e,f,g,h)        static const Br _b[] = {{a,b},{c,d},{e,f},{g,h}}; (void)_b

// ---------------------------------------------------------------------------------------------
// the 110 rows
// ---------------------------------------------------------------------------------------------

#define R_(name) static bool name(const Mol& m, int i)

// ---- carbon, aliphatic ----------------------------------------------------------------------
R_(r000) { return m.sh[i] == 4; }                                              // C1  [CH4]
R_(r001) { return m.sh[i] == 3 && hasNbr(m, i, BM_ANY, q_aliC); }              // C1  [CH3]C
R_(r002) { B2(BM_ANY, q_aliC, BM_ANY, q_aliC);                                 // C1  [CH2](C)C
           return m.sh[i] == 2 && branches(m, i, -1, _b, 2); }
R_(r003) { B3(BM_ANY, q_aliC, BM_ANY, q_aliC, BM_ANY, q_aliC);                 // C2  [CH](C)(C)C
           return m.sh[i] == 1 && branches(m, i, -1, _b, 3); }
R_(r004) { B4(BM_ANY, q_aliC, BM_ANY, q_aliC, BM_ANY, q_aliC, BM_ANY, q_aliC); // C2  [C](C)(C)(C)C
           return branches(m, i, -1, _b, 4); }
R_(r005) { return m.sh[i] == 3 && hasNbr(m, i, BM_ANY, q_C3het); }             // C3  [CH3][N,O,...]
R_(r006) { B2(BM_ANY, q_C3het, BM_ANY, q_aliHeavy);                            // C3  [CH2X4](het)[A;!#1]
           return m.sh[i] == 2 && m.tx[i] == 4 && branches(m, i, -1, _b, 2); }
R_(r007) { B3(BM_ANY, q_C3het, BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);        // C4
           return m.sh[i] == 1 && m.tx[i] == 4 && branches(m, i, -1, _b, 3); }
R_(r008) { B4(BM_ANY, q_C3het, BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);
           return m.sh[i] == 0 && m.tx[i] == 4 && branches(m, i, -1, _b, 4); }  // C4
R_(r009) { return hasNbr(m, i, B_DOUBLE, q_aliHeavyNotC); }                    // C5  [C]=[!C;A;!#1]
R_(r010) { return m.sh[i] == 2 && hasNbr(m, i, B_DOUBLE, q_aliC); }            // C6  [CH2]=C
R_(r011) { B2(B_DOUBLE, q_aliC, BM_ANY, q_aliHeavy);                           // C6  [CH1](=C)[A;!#1]
           return m.sh[i] == 1 && branches(m, i, -1, _b, 2); }
R_(r012) { B3(B_DOUBLE, q_aliC, BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);       // C6  [CH0](=C)(A)A
           return m.sh[i] == 0 && branches(m, i, -1, _b, 3); }
R_(r013) { B2(B_DOUBLE, q_aliC, B_DOUBLE, q_aliC);                             // C6  [C](=C)=C
           return branches(m, i, -1, _b, 2); }
R_(r014) { return m.tx[i] == 2 && hasNbr(m, i, B_TRIPLE, q_aliHeavy); }        // C7  [CX2]#[A;!#1]
R_(r015) { return m.sh[i] == 3 && hasNbr(m, i, BM_ANY, q_aroC); }              // C8  [CH3]c
R_(r016) { return m.sh[i] == 3 && hasNbr(m, i, BM_ANY, q_aro); }               // C9  [CH3]a
R_(r017) { return m.sh[i]==2 && m.tx[i]==4 && hasNbr(m,i,BM_ANY,q_aro); }      // C10 [CH2X4]a
R_(r018) { return m.sh[i]==1 && m.tx[i]==4 && hasNbr(m,i,BM_ANY,q_aro); }      // C11 [CHX4]a
R_(r019) { return m.sh[i]==0 && m.tx[i]==4 && hasNbr(m,i,BM_ANY,q_aro); }      // C12 [CH0X4]a

// ---- carbon, aromatic -----------------------------------------------------------------------
R_(r020) { return m.sh[i] == 0 && hasNbr(m, i, B_SINGLE, q_C13nbr); }          // C13 [cH0]-[...]
R_(r021) { return hasNbr(m, i, BM_ANY, q_z9);  }                               // C14 [c][#9]
R_(r022) { return hasNbr(m, i, BM_ANY, q_z17); }                               // C15 [c][#17]
R_(r023) { return hasNbr(m, i, BM_ANY, q_z35); }                               // C16 [c][#35]
R_(r024) { return hasNbr(m, i, BM_ANY, q_z53); }                               // C17 [c][#53]
R_(r025) { return m.sh[i] == 1; }                                              // C18 [cH]
R_(r026) { B3(B_AROM, q_aro, B_AROM, q_aro, B_AROM, q_aro);                    // C19 [c](:a)(:a):a
           return branches(m, i, -1, _b, 3); }
R_(r027) { B3(B_AROM, q_aro, B_AROM, q_aro, B_SINGLE, q_aro);                  // C20 [c](:a)(:a)-a
           return branches(m, i, -1, _b, 3); }
R_(r028) { B3(B_AROM, q_aro, B_AROM, q_aro, B_SINGLE, q_aliC);                 // C21 -C
           return branches(m, i, -1, _b, 3); }
R_(r029) { B3(B_AROM, q_aro, B_AROM, q_aro, B_SINGLE, q_aliN);                 // C22 -N
           return branches(m, i, -1, _b, 3); }
R_(r030) { B3(B_AROM, q_aro, B_AROM, q_aro, B_SINGLE, q_aliO);                 // C23 -O
           return branches(m, i, -1, _b, 3); }
R_(r031) { B3(B_AROM, q_aro, B_AROM, q_aro, B_SINGLE, q_aliS);                 // C24 -S
           return branches(m, i, -1, _b, 3); }
R_(r032) { B3(B_AROM, q_aro, B_AROM, q_aro, B_DOUBLE, q_C25nbr);               // C25 =[C,N,O]
           return branches(m, i, -1, _b, 3); }

// ---- carbon, C26/C27/CS ---------------------------------------------------------------------
R_(r033) { B3(B_DOUBLE, q_aliC, BM_ANY, q_aro, BM_ANY, q_aliHeavy);            // C26 [C](=C)(a)[A;!#1]
           return branches(m, i, -1, _b, 3); }
R_(r034) { B3(B_DOUBLE, q_aliC, BM_ANY, q_aroC, BM_ANY, q_aro);                // C26 [C](=C)(c)a
           return branches(m, i, -1, _b, 3); }
R_(r035) { B2(B_DOUBLE, q_aliC, BM_ANY, q_aro);                                // C26 [CH1](=C)a
           return m.sh[i] == 1 && branches(m, i, -1, _b, 2); }
R_(r036) { return hasNbr(m, i, B_DOUBLE, q_aroC); }                            // C26 [C]=c
R_(r037) { return m.tx[i] == 4 && hasNbr(m, i, BM_ANY, q_C27nbr); }            // C27 [CX4][...]
R_(r038) { (void)m; (void)i; return true; }                                    // CS  [#6]

// ---- hydrogen -------------------------------------------------------------------------------
R_(r039) { return hasNbr(m, i, BM_ANY, q_H1nbr); }                             // H1  [#1][#6,#1]
// H2/H3/H4 reach past the first shell: H -O- X. The trigger is cheap (an aliphatic O neighbour)
// and the second shell is that ONE oxygen's other substituents, with the H itself excluded so the
// query atoms stay distinct.
#define THRU_O(inner_bm, inner_q)                                                        \
  for (int e = m.start[i]; e < m.start[i + 1]; ++e) {                                    \
    if (!(m.bcode[e] & BM_ANY)) continue;                                                \
    int o = m.nbr[e];                                                                    \
    if (!q_aliO(m, o)) continue;                                                         \
    B1(inner_bm, inner_q);                                                               \
    if (branches(m, o, i, _b, 1)) return true;                                           \
  }                                                                                      \
  return false

R_(r040) { THRU_O(BM_ANY, q_CX4orAroC); }                                      // H2 [#1]O[CX4,c]
R_(r041) { THRU_O(BM_ANY, q_notCNOS);   }                                      // H2 [#1]O[!#6;!#7;!#8;!#16]
R_(r042) { return hasNbr(m, i, BM_ANY, q_notCNO); }                            // H2 [#1][!#6;!#7;!#8]
R_(r043) { return hasNbr(m, i, BM_ANY, q_anyN); }                              // H3 [#1][#7]
R_(r044) { THRU_O(BM_ANY, q_anyN);      }                                      // H3 [#1]O[#7]
R_(r045) {                                                                     // H4 [#1]OC=[#6,#7,O,S]
  // the one depth-3 row in the whole table: H-O-C=X
  for (int e = m.start[i]; e < m.start[i + 1]; ++e) {
    if (!(m.bcode[e] & BM_ANY)) continue;
    int o = m.nbr[e];
    if (!q_aliO(m, o)) continue;
    for (int f = m.start[o]; f < m.start[o + 1]; ++f) {
      if (!(m.bcode[f] & BM_ANY)) continue;
      int c = m.nbr[f];
      if (c == i || !q_aliC(m, c)) continue;
      for (int g = m.start[c]; g < m.start[c + 1]; ++g) {
        if (!(m.bcode[g] & B_DOUBLE)) continue;
        int x = m.nbr[g];
        if (x == o || x == i) continue;
        if (q_H4dbl(m, x)) return true;
      }
    }
  }
  return false;
}
R_(r046) { THRU_O(BM_ANY, q_aliOorS);   }                                      // H4 [#1]O[O,S]
R_(r047) { (void)m; (void)i; return true; }                                    // HS [#1]
#undef THRU_O

// ---- nitrogen -------------------------------------------------------------------------------
R_(r048) { return m.sh[i]==2 && m.chg[i]==0 && hasNbr(m,i,BM_ANY,q_aliHeavy); }  // N1
R_(r049) { B2(BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);                           // N2
           return m.sh[i]==1 && m.chg[i]==0 && branches(m, i, -1, _b, 2); }
R_(r050) { return m.sh[i]==2 && m.chg[i]==0 && hasNbr(m,i,BM_ANY,q_aro); }       // N3  [NH2+0]a
R_(r051) { B2(BM_ANY, q_heavy, BM_ANY, q_aro);                                   // N4
           return m.sh[i]==1 && m.chg[i]==0 && branches(m, i, -1, _b, 2); }
R_(r052) { return m.sh[i]==1 && m.chg[i]==0 && hasNbr(m,i,B_DOUBLE,q_heavy); }   // N5
R_(r053) { B2(B_DOUBLE, q_heavy, BM_ANY, q_heavy);                               // N6
           return m.chg[i]==0 && branches(m, i, -1, _b, 2); }
R_(r054) { B3(BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);       // N7
           return m.chg[i]==0 && branches(m, i, -1, _b, 3); }
R_(r055) { B3(BM_ANY, q_aro, BM_ANY, q_heavy, BM_ANY, q_aliHeavy);               // N8
           return m.chg[i]==0 && branches(m, i, -1, _b, 3); }
R_(r056) { B3(BM_ANY, q_aro, BM_ANY, q_aro, BM_ANY, q_aro);                      // N8 (a)(a)a
           return m.chg[i]==0 && branches(m, i, -1, _b, 3); }
R_(r057) { return m.chg[i]==0 && hasNbr(m,i,B_TRIPLE,q_aliHeavy); }              // N9
R_(r058) { return m.sh[i]>=1 && m.sh[i]<=3 && m.chg[i]>=1 && m.chg[i]<=3; }      // N10
R_(r059) { return m.chg[i] == 0; }                                               // N11 [n+0]
R_(r060) { return m.chg[i] >= 1 && m.chg[i] <= 3; }                              // N12 [n;+,+2,+3]
R_(r061) { B4(BM_ANY,q_aliHeavy, BM_ANY,q_aliHeavy, BM_ANY,q_aliHeavy, BM_ANY,q_aliHeavy);
           return m.sh[i]==0 && m.chg[i]>=1 && m.chg[i]<=3 && branches(m, i, -1, _b, 4); }  // N13
R_(r062) { B3(B_DOUBLE, q_aliHeavy, BM_ANY, q_aliHeavy, BM_ANY, q_heavy);        // N13
           return m.sh[i]==0 && m.chg[i]>=1 && m.chg[i]<=3 && branches(m, i, -1, _b, 3); }
R_(r063) { B2(B_DOUBLE, q_anyC, B_DOUBLE, q_anyN);                               // N13 (=[#6])=[#7]
           return m.sh[i]==0 && m.chg[i]>=1 && m.chg[i]<=3 && branches(m, i, -1, _b, 2); }
R_(r064) { return m.chg[i]>=1 && m.chg[i]<=3 && hasNbr(m,i,B_TRIPLE,q_aliHeavy); }  // N14
R_(r065) { return m.chg[i] <= -1 && m.chg[i] >= -3; }                            // N14 [N;-,-2,-3]
R_(r066) { B2(B_DOUBLE, q_aliNneg, B_DOUBLE, q_aliN);                            // N14 (=[N-])=N
           return m.chg[i]>=1 && m.chg[i]<=3 && branches(m, i, -1, _b, 2); }
R_(r067) { (void)m; (void)i; return true; }                                      // NS [#7]

// ---- oxygen ---------------------------------------------------------------------------------
R_(r068) { (void)m; (void)i; return true; }                                      // O1 [o]
R_(r069) { return m.sh[i] == 1 || m.sh[i] == 2; }                                // O2 [OH,OH2]
R_(r070) { B2(BM_ANY, q_aliHeavy, BM_ANY, q_aliHeavy);                           // O3
           return branches(m, i, -1, _b, 2); }
R_(r071) { B2(BM_ANY, q_aro, BM_ANY, q_heavy);                                   // O4
           return branches(m, i, -1, _b, 2); }
R_(r072) { return hasNbr(m, i, B_DOUBLE, q_z7or8); }                             // O5 [O]=[#7,#8]
R_(r073) { return m.tx[i]==1 && m.chg[i]<=-1 && m.chg[i]>=-3 &&                  // O5 [OX1;-..][#7]
                  hasNbr(m, i, BM_ANY, q_anyN); }
R_(r074) { return m.tx[i]==1 && m.chg[i]<=-1 && m.chg[i]>=-2 &&                  // O6 [OX1;-,-2][#16]
                  hasNbr(m, i, BM_ANY, q_z16); }
R_(r075) { return m.chg[i]==0 && hasNbr(m, i, B_DOUBLE, q_z16chg0); }            // O6 [O;-0]=[#16;-0]
R_(r076) {                                                                       // O12 [O-]C(=O)
  if (m.chg[i] != -1) return false;
  for (int e = m.start[i]; e < m.start[i + 1]; ++e) {
    if (!(m.bcode[e] & BM_ANY)) continue;
    int c = m.nbr[e];
    if (!q_aliC(m, c)) continue;
    B1(B_DOUBLE, q_aliO);
    if (branches(m, c, i, _b, 1)) return true;
  }
  return false;
}
R_(r077) { return m.tx[i]==1 && m.chg[i]<=-1 && m.chg[i]>=-3 &&                  // O7
                  hasNbr(m, i, BM_ANY, q_O7nbr); }
R_(r078) { return hasNbr(m, i, B_DOUBLE, q_aroC); }                              // O8 [O]=c

// O9/O10/O11 all share the trigger "double-bonded to an aliphatic carbon"; what differs is what
// that carbon's OTHER substituents must be. Written once as a loop over candidate carbons.
#define THRU_C(guard, nbranch, ...)                                                      \
  for (int e = m.start[i]; e < m.start[i + 1]; ++e) {                                    \
    if (!(m.bcode[e] & B_DOUBLE)) continue;                                              \
    int c = m.nbr[e];                                                                    \
    if (!q_aliC(m, c)) continue;                                                         \
    if (!(guard)) continue;                                                              \
    static const Br _b[] = {__VA_ARGS__};                                                \
    if (branches(m, c, i, _b, nbranch)) return true;                                     \
  }                                                                                      \
  return false

R_(r079) { THRU_C(m.sh[c] == 1, 1, {BM_ANY, q_aliC}); }                          // O9  [O]=[CH]C
R_(r080) { THRU_C(true, 2, {BM_ANY, q_aliC}, {BM_ANY, q_aliHeavy}); }            // O9  [O]=C(C)(A)
R_(r081) { THRU_C(m.sh[c] == 1, 1, {BM_ANY, q_aliNorO}); }                       // O9  [O]=[CH][N,O]
R_(r082) { for (int e = m.start[i]; e < m.start[i+1]; ++e)                        // O9  [O]=[CH2]
             if ((m.bcode[e] & B_DOUBLE) && q_aliC(m, m.nbr[e]) && m.sh[m.nbr[e]] == 2)
               return true;
           return false; }
R_(r083) { THRU_C(m.tx[c] == 2, 1, {B_DOUBLE, q_aliO}); }                        // O9  [O]=[CX2]=O
R_(r084) { THRU_C(m.sh[c] == 1, 1, {BM_ANY, q_aroC}); }                          // O10 [O]=[CH]c
R_(r085) { THRU_C(true, 2, {BM_ANY, q_anyC}, {BM_ANY, q_aroHeavy}); }            // O10 [O]=C([C,c])[a;!#1]
R_(r086) { THRU_C(true, 2, {BM_ANY, q_aroC}, {BM_ANY, q_aliHeavy}); }            // O10 [O]=C(c)[A;!#1]
R_(r087) { THRU_C(true, 2, {BM_ANY, q_notHC}, {BM_ANY, q_notHC}); }              // O11
#undef THRU_C
R_(r088) { (void)m; (void)i; return true; }                                      // OS [#8]

// ---- halogen, metals, P, S ------------------------------------------------------------------
R_(r089) { return m.chg[i] == 0; }                                               // F   [#9-0]
R_(r090) { return m.chg[i] == 0; }                                               // Cl  [#17-0]
R_(r091) { return m.chg[i] == 0; }                                               // Br  [#35-0]
R_(r092) { return m.chg[i] == 0; }                                               // I   [#53-0]
R_(r093) { return m.chg[i] == -1; }                                              // Hal [#9,#17,#35,#53;-]
R_(r094) { return m.chg[i] >= 1 && m.chg[i] <= 3; }                              // Hal [#53;+,+2,+3]
R_(r095) { return m.chg[i] == 1; }                                               // Hal [+;#3,#11,...]
R_(r096) { (void)m; (void)i; return true; }                                      // P   [#15]
R_(r097) { int c = m.chg[i];                                                     // S2  [S;-,..,+6]
           return (c >= -4 && c <= -1) || c == 1 || c == 2 || c == 3 || c == 5 || c == 6; }
R_(r098) { return m.chg[i]==0 && hasNbr(m, i, B_DOUBLE, q_S2nbr); }              // S2  [S-0]=[N,O,P,S]
R_(r099) { (void)m; (void)i; return true; }                                      // S1  [S;A]
R_(r100) { (void)m; (void)i; return true; }                                      // S3  [s;a]
R_(r101) { (void)m; (void)i; return true; }                                      // Me1 alkali
R_(r102) { (void)m; (void)i; return true; }                                      // Me1 alkaline earth
R_(r103) { (void)m; (void)i; return true; }                                      // Me1 B/Al/Ga/In/Tl
R_(r104) { (void)m; (void)i; return true; }                                      // Me1 Si/Ge/Sn/Pb
R_(r105) { (void)m; (void)i; return true; }                                      // Me1 As/Sb/Bi
R_(r106) { (void)m; (void)i; return true; }                                      // Me1 Se/Te/Po
R_(r107) { (void)m; (void)i; return true; }                                      // Me2 3d
R_(r108) { (void)m; (void)i; return true; }                                      // Me2 4d
R_(r109) { (void)m; (void)i; return true; }                                      // Me2 5d

#undef R_
#undef B1
#undef B2
#undef B3
#undef B4

// Each predicate is stored next to the SMARTS it claims to implement, together with the element
// and aromaticity its FIRST atom demands. selfCheck() compares the strings against the generated
// table, so an RDKit release that edits or reorders a row is a startup failure rather than a
// silent numeric change; the {aro, zs} fields are the single source for the dispatch below, so
// there is no second hand-maintained list to fall out of step.
//
//   aro: -1 the row's first atom says nothing about aromaticity ([#6], [#1], [#15], ...)
//         0 it is an ALIPHATIC element symbol ([C], [NH2+0], [OX1;-], [S;A], ...)
//         1 it is an AROMATIC element symbol ([c], [n+0], [o], [s;a])
//   zs : the atomic numbers the first atom admits, 0-terminated
struct Impl { const char* smarts; bool (*fn)(const Mol&, int); int8_t aro; uint8_t zs[11]; };

#define C_ {6, 0}
#define c_ {6, 0}
#define N_ {7, 0}
#define O_ {8, 0}
#define S_ {16, 0}
#define H_ {1, 0}

static const Impl IMPL[crippen::N_ROWS] = {
  {"[CH4]", r000, 0, C_}, {"[CH3]C", r001, 0, C_}, {"[CH2](C)C", r002, 0, C_},
  {"[CH](C)(C)C", r003, 0, C_}, {"[C](C)(C)(C)C", r004, 0, C_},
  {"[CH3][N,O,P,S,F,Cl,Br,I]", r005, 0, C_},
  {"[CH2X4]([N,O,P,S,F,Cl,Br,I])[A;!#1]", r006, 0, C_},
  {"[CH1X4]([N,O,P,S,F,Cl,Br,I])([A;!#1])[A;!#1]", r007, 0, C_},
  {"[CH0X4]([N,O,P,S,F,Cl,Br,I])([A;!#1])([A;!#1])[A;!#1]", r008, 0, C_},
  {"[C]=[!C;A;!#1]", r009, 0, C_}, {"[CH2]=C", r010, 0, C_},
  {"[CH1](=C)[A;!#1]", r011, 0, C_}, {"[CH0](=C)([A;!#1])[A;!#1]", r012, 0, C_},
  {"[C](=C)=C", r013, 0, C_}, {"[CX2]#[A;!#1]", r014, 0, C_},
  {"[CH3]c", r015, 0, C_}, {"[CH3]a", r016, 0, C_}, {"[CH2X4]a", r017, 0, C_},
  {"[CHX4]a", r018, 0, C_}, {"[CH0X4]a", r019, 0, C_},
  {"[cH0]-[A;!C;!N;!O;!S;!F;!Cl;!Br;!I;!#1]", r020, 1, c_},
  {"[c][#9]", r021, 1, c_}, {"[c][#17]", r022, 1, c_}, {"[c][#35]", r023, 1, c_},
  {"[c][#53]", r024, 1, c_}, {"[cH]", r025, 1, c_}, {"[c](:a)(:a):a", r026, 1, c_},
  {"[c](:a)(:a)-a", r027, 1, c_}, {"[c](:a)(:a)-C", r028, 1, c_},
  {"[c](:a)(:a)-N", r029, 1, c_}, {"[c](:a)(:a)-O", r030, 1, c_},
  {"[c](:a)(:a)-S", r031, 1, c_}, {"[c](:a)(:a)=[C,N,O]", r032, 1, c_},
  {"[C](=C)(a)[A;!#1]", r033, 0, C_}, {"[C](=C)(c)a", r034, 0, C_},
  {"[CH1](=C)a", r035, 0, C_}, {"[C]=c", r036, 0, C_},
  {"[CX4][A;!C;!N;!O;!P;!S;!F;!Cl;!Br;!I;!#1]", r037, 0, C_}, {"[#6]", r038, -1, C_},
  {"[#1][#6,#1]", r039, -1, H_}, {"[#1]O[CX4,c]", r040, -1, H_},
  {"[#1]O[!#6;!#7;!#8;!#16]", r041, -1, H_}, {"[#1][!#6;!#7;!#8]", r042, -1, H_},
  {"[#1][#7]", r043, -1, H_}, {"[#1]O[#7]", r044, -1, H_},
  {"[#1]OC=[#6,#7,O,S]", r045, -1, H_}, {"[#1]O[O,S]", r046, -1, H_}, {"[#1]", r047, -1, H_},
  {"[NH2+0][A;!#1]", r048, 0, N_}, {"[NH+0]([A;!#1])[A;!#1]", r049, 0, N_},
  {"[NH2+0]a", r050, 0, N_}, {"[NH1+0]([!#1;A,a])a", r051, 0, N_},
  {"[NH+0]=[!#1;A,a]", r052, 0, N_}, {"[N+0](=[!#1;A,a])[!#1;A,a]", r053, 0, N_},
  {"[N+0]([A;!#1])([A;!#1])[A;!#1]", r054, 0, N_},
  {"[N+0](a)([!#1;A,a])[A;!#1]", r055, 0, N_}, {"[N+0](a)(a)a", r056, 0, N_},
  {"[N+0]#[A;!#1]", r057, 0, N_}, {"[NH3,NH2,NH;+,+2,+3]", r058, 0, N_},
  {"[n+0]", r059, 1, N_}, {"[n;+,+2,+3]", r060, 1, N_},
  {"[NH0;+,+2,+3]([A;!#1])([A;!#1])([A;!#1])[A;!#1]", r061, 0, N_},
  {"[NH0;+,+2,+3](=[A;!#1])([A;!#1])[!#1;A,a]", r062, 0, N_},
  {"[NH0;+,+2,+3](=[#6])=[#7]", r063, 0, N_}, {"[N;+,+2,+3]#[A;!#1]", r064, 0, N_},
  {"[N;-,-2,-3]", r065, 0, N_}, {"[N;+,+2,+3](=[N;-,-2,-3])=N", r066, 0, N_},
  {"[#7]", r067, -1, N_},
  {"[o]", r068, 1, O_}, {"[OH,OH2]", r069, 0, O_}, {"[O]([A;!#1])[A;!#1]", r070, 0, O_},
  {"[O](a)[!#1;A,a]", r071, 0, O_}, {"[O]=[#7,#8]", r072, 0, O_},
  {"[OX1;-,-2,-3][#7]", r073, 0, O_}, {"[OX1;-,-2,-2][#16]", r074, 0, O_},
  {"[O;-0]=[#16;-0]", r075, 0, O_}, {"[O-]C(=O)", r076, 0, O_},
  {"[OX1;-,-2,-3][!#1;!N;!S]", r077, 0, O_}, {"[O]=c", r078, 0, O_},
  {"[O]=[CH]C", r079, 0, O_}, {"[O]=C(C)([A;!#1])", r080, 0, O_},
  {"[O]=[CH][N,O]", r081, 0, O_}, {"[O]=[CH2]", r082, 0, O_},
  {"[O]=[CX2]=O", r083, 0, O_}, {"[O]=[CH]c", r084, 0, O_},
  {"[O]=C([C,c])[a;!#1]", r085, 0, O_}, {"[O]=C(c)[A;!#1]", r086, 0, O_},
  {"[O]=C([!#1;!#6])[!#1;!#6]", r087, 0, O_}, {"[#8]", r088, -1, O_},
  {"[#9-0]", r089, -1, {9, 0}}, {"[#17-0]", r090, -1, {17, 0}},
  {"[#35-0]", r091, -1, {35, 0}}, {"[#53-0]", r092, -1, {53, 0}},
  {"[#9,#17,#35,#53;-]", r093, -1, {9, 17, 35, 53, 0}},
  {"[#53;+,+2,+3]", r094, -1, {53, 0}},
  {"[+;#3,#11,#19,#37,#55]", r095, -1, {3, 11, 19, 37, 55, 0}},
  {"[#15]", r096, -1, {15, 0}},
  {"[S;-,-2,-3,-4,+1,+2,+3,+5,+6]", r097, 0, S_}, {"[S-0]=[N,O,P,S]", r098, 0, S_},
  {"[S;A]", r099, 0, S_}, {"[s;a]", r100, 1, S_},
  {"[#3,#11,#19,#37,#55]", r101, -1, {3, 11, 19, 37, 55, 0}},
  {"[#4,#12,#20,#38,#56]", r102, -1, {4, 12, 20, 38, 56, 0}},
  {"[#5,#13,#31,#49,#81]", r103, -1, {5, 13, 31, 49, 81, 0}},
  {"[#14,#32,#50,#82]", r104, -1, {14, 32, 50, 82, 0}},
  {"[#33,#51,#83]", r105, -1, {33, 51, 83, 0}},
  {"[#34,#52,#84]", r106, -1, {34, 52, 84, 0}},
  {"[#21,#22,#23,#24,#25,#26,#27,#28,#29,#30]", r107, -1, {21,22,23,24,25,26,27,28,29,30, 0}},
  {"[#39,#40,#41,#42,#43,#44,#45,#46,#47,#48]", r108, -1, {39,40,41,42,43,44,45,46,47,48, 0}},
  {"[#72,#73,#74,#75,#76,#77,#78,#79,#80]", r109, -1, {72,73,74,75,76,77,78,79,80, 0}},
};

#undef C_
#undef c_
#undef N_
#undef O_
#undef S_
#undef H_

// ---------------------------------------------------------------------------------------------
// dispatch: which rows can an atom of this (element, aromaticity) possibly match, in row order
//
// Every row's first atom constrains the element, so this partition loses nothing. It is BUILT
// from the {aro, zs} fields above rather than hand-listed, so it cannot disagree with them; and
// `crippen paranoid` additionally re-runs the corpus through the undispatched all-110-rows-in-
// order path to prove the precomputed lists reproduce a plain linear scan atom for atom.
// ---------------------------------------------------------------------------------------------

static uint8_t DISP[119][2][crippen::N_ROWS];
static int     DISP_N[119][2];

static inline bool rowAdmits(int r, int z, int arom) {
  const Impl& im = IMPL[r];
  if (im.aro >= 0 && im.aro != arom) return false;
  for (int k = 0; k < 11 && im.zs[k]; ++k) if (im.zs[k] == z) return true;
  return false;
}

static void buildDispatch() {
  for (int z = 0; z < 119; ++z)
    for (int a = 0; a < 2; ++a) {
      int n = 0;
      for (int r = 0; r < crippen::N_ROWS; ++r) if (rowAdmits(r, z, a)) DISP[z][a][n++] = (uint8_t)r;
      DISP_N[z][a] = n;
    }
}

// -> row index, or -1 for "no pattern claims this atom" (contribution stays 0,0)
static inline int typeAtom(const Mol& m, int i) {
  int z = m.z[i], a = m.arom[i] ? 1 : 0;
  if (z > 118) return -1;
  const uint8_t* L = DISP[z][a];
  int n = DISP_N[z][a];
  for (int k = 0; k < n; ++k) if (IMPL[L[k]].fn(m, i)) return L[k];
  return -1;
}

// The undispatched reference path: every row, in file order, guard evaluated inline.
static int typeAtomSlow(const Mol& m, int i) {
  int z = m.z[i], a = m.arom[i] ? 1 : 0;
  if (z > 118) return -1;
  for (int r = 0; r < crippen::N_ROWS; ++r)
    if (rowAdmits(r, z, a) && IMPL[r].fn(m, i)) return r;
  return -1;
}

static void contribs(const Mol& m, double* logp, double* mr) {
  for (int i = 0; i < m.n; ++i) {
    int r = typeAtom(m, i);
    if (r < 0) { logp[i] = crippen::UNMATCHED_LOGP; mr[i] = crippen::UNMATCHED_MR; }
    else       { logp[i] = crippen::ROWS[r].logp;   mr[i] = crippen::ROWS[r].mr;   }
  }
}

// ---------------------------------------------------------------------------------------------
// io / harness
// ---------------------------------------------------------------------------------------------

static void selfCheck() {
  for (int r = 0; r < crippen::N_ROWS; ++r) {
    if (std::strcmp(IMPL[r].smarts, crippen::ROWS[r].smarts) != 0) {
      std::fprintf(stderr,
        "FATAL: row %d drifted. crippen_tables.h says\n  %s\nbut crippen.cpp implements\n  %s\n"
        "Regenerate the table and re-derive the predicate; do NOT paper over this.\n",
        r, crippen::ROWS[r].smarts, IMPL[r].smarts);
      std::exit(2);
    }
  }
}

static std::vector<Mol> load(const char* path) {
  FILE* f = std::fopen(path, "r");
  if (!f) { std::fprintf(stderr, "cannot open %s (run export_crippen.py mols)\n", path); std::exit(1); }
  int nm = 0;
  if (std::fscanf(f, "%d", &nm) != 1) std::exit(1);
  std::vector<Mol> out(nm);
  for (int k = 0; k < nm; ++k) {
    Mol& m = out[k];
    int nb = 0;
    if (std::fscanf(f, "%d %d", &m.n, &nb) != 2) std::exit(1);
    m.z.resize(m.n); m.arom.resize(m.n); m.sh.resize(m.n); m.tx.resize(m.n);
    m.deg.resize(m.n); m.chg.resize(m.n);
    std::vector<int> nHp(m.n), deg(m.n);
    for (int i = 0; i < m.n; ++i) {
      int z, d, nh, c, ar;
      if (std::fscanf(f, "%d %d %d %d %d", &z, &d, &nh, &c, &ar) != 5) std::exit(1);
      m.z[i] = (uint8_t)(z > 255 ? 255 : z); m.deg[i] = (uint8_t)d; nHp[i] = nh;
      m.chg[i] = (int8_t)c; m.arom[i] = (uint8_t)ar; deg[i] = d;
      m.tx[i] = (uint8_t)(d + nh);                       // SMARTS X == getTotalDegree()
      m.sh[i] = (uint8_t)nh;                             // + explicit H neighbours, added below
    }
    std::vector<int> eu(nb), ev(nb), ec(nb);
    std::vector<int> cnt(m.n + 1, 0);
    for (int e = 0; e < nb; ++e) {
      if (std::fscanf(f, "%d %d %d", &eu[e], &ev[e], &ec[e]) != 3) std::exit(1);
      cnt[eu[e]]++; cnt[ev[e]]++;
    }
    m.start.assign(m.n + 1, 0);
    for (int i = 0; i < m.n; ++i) m.start[i + 1] = m.start[i] + cnt[i];
    m.nbr.resize(2 * nb); m.bcode.resize(2 * nb);
    std::vector<int> cur(m.start.begin(), m.start.end() - 1);
    for (int e = 0; e < nb; ++e) {
      m.nbr[cur[eu[e]]] = ev[e]; m.bcode[cur[eu[e]]++] = (uint8_t)ec[e];
      m.nbr[cur[ev[e]]] = eu[e]; m.bcode[cur[ev[e]]++] = (uint8_t)ec[e];
    }
    // SMARTS `H` counts neighbouring explicit H ATOMS as well as the implicit count.
    for (int i = 0; i < m.n; ++i) {
      int extra = 0;
      for (int e = m.start[i]; e < m.start[i + 1]; ++e) if (m.z[m.nbr[e]] == 1) ++extra;
      m.sh[i] = (uint8_t)(nHp[i] + extra);
    }
    m.ref_logp.resize(m.n); m.ref_mr.resize(m.n); m.ref_row.resize(m.n);
    for (int i = 0; i < m.n; ++i) {
      int rr;
      if (std::fscanf(f, "%d %lf %lf", &rr, &m.ref_logp[i], &m.ref_mr[i]) != 3) std::exit(1);
      m.ref_row[i] = (uint8_t)rr;
    }
  }
  std::fclose(f);
  return out;
}

static int verify(const char* path, bool paranoid) {
  std::vector<Mol> mols = load(path);
  long long nat = 0, nbad = 0, nvalbad = 0, nmolbad = 0;
  std::vector<long long> okc(crippen::N_CLASSES + 1, 0), badc(crippen::N_CLASSES + 1, 0);
  std::vector<long long> rowhit(crippen::N_ROWS, 0);
  int shown = 0;
  for (size_t k = 0; k < mols.size(); ++k) {
    const Mol& m = mols[k];
    bool molbad = false;
    for (int i = 0; i < m.n; ++i) {
      int r = typeAtom(m, i);
      if (paranoid && typeAtomSlow(m, i) != r) {
        std::fprintf(stderr, "PARANOID: dispatch disagrees at mol %zu atom %d\n", k, i);
        return 3;
      }
      double lp = r < 0 ? crippen::UNMATCHED_LOGP : crippen::ROWS[r].logp;
      double mr = r < 0 ? crippen::UNMATCHED_MR   : crippen::ROWS[r].mr;
      int rr  = m.ref_row[i] == 255 ? -1 : (int)m.ref_row[i];
      int cls = rr < 0 ? crippen::N_CLASSES : crippen::ROW_CLASS[rr];
      ++nat;
      if (rr >= 0) ++rowhit[rr];
      // Compare the ROW RDKit picked, not just the numbers it produced. Two compensating
      // per-atom errors cancel in a molecule total; two classes with equal (logP, MR) would
      // cancel even per atom. The row index admits neither. The value check below is then a
      // second, independent assertion that the generated table itself is right.
      if (rr != r) {
        ++badc[cls]; ++nbad; molbad = true;
        if (shown < 25) {
          ++shown;
          std::fprintf(stderr,
            "  mol %zu atom %d Z=%d arom=%d chg=%d H=%d X=%d deg=%d : "
            "got row %d %s (%.6g,%.6g) want row %d %s (%.6g,%.6g)\n",
            k, i, (int)m.z[i], (int)m.arom[i], (int)m.chg[i], (int)m.sh[i], (int)m.tx[i],
            (int)m.deg[i], r, r < 0 ? "-" : crippen::ROWS[r].cls, lp, mr,
            rr, rr < 0 ? "-" : crippen::ROWS[rr].cls, m.ref_logp[i], m.ref_mr[i]);
        }
      } else {
        ++okc[cls];
        // EXACT. These are table lookups from the same source RDKit uses; widening this to a
        // tolerance could only ever hide a wrong number.
        if (lp != m.ref_logp[i] || mr != m.ref_mr[i]) { ++nvalbad; molbad = true; }
      }
    }
    if (molbad) ++nmolbad;
  }
  std::printf("\nper-atom exactness vs RDKit _CalcCrippenContribs\n");
  std::printf("  %zu molecules, %lld atoms\n", mols.size(), nat);
  std::printf("  same row picked : %lld / %lld  (%.6f%%)\n", nat - nbad, nat,
              100.0 * (double)(nat - nbad) / (double)nat);
  std::printf("  (logP, MR) exact: %lld / %lld  (%.6f%%)\n", nat - nbad - nvalbad, nat,
              100.0 * (double)(nat - nbad - nvalbad) / (double)nat);
  std::printf("  molecules exact : %lld / %lld\n", (long long)(mols.size() - nmolbad),
              (long long)mols.size());
  std::printf("\n  %-8s %12s %10s %9s\n", "class", "atoms", "exact", "pct");
  for (int c = 0; c <= crippen::N_CLASSES; ++c) {
    long long t = okc[c] + badc[c];
    const char* nm = c == crippen::N_CLASSES ? "(none)" : crippen::CLASS_NAMES[c];
    if (t == 0) { std::printf("  %-8s %12s %10s %9s   NEVER FIRES - UNTESTED\n", nm, "0", "-", "-"); continue; }
    std::printf("  %-8s %12lld %10lld %8.4f%%%s\n", nm, t, okc[c], 100.0 * (double)okc[c] / (double)t,
                badc[c] ? "   <-- MISMATCH" : "");
  }
  // Per-CLASS is what the report asks for, but a class can look green while one of its rows has
  // never been exercised (C1 has three rows, C26 four, O9 five). List those explicitly.
  int nz = 0;
  for (int r = 0; r < crippen::N_ROWS; ++r) if (!rowhit[r]) ++nz;
  std::printf("\n  rows never exercised by this corpus: %d / %d\n", nz, crippen::N_ROWS);
  for (int r = 0; r < crippen::N_ROWS; ++r)
    if (!rowhit[r]) std::printf("    row %-3d %-4s %s\n", r, crippen::ROWS[r].cls,
                                crippen::ROWS[r].smarts);
  if (paranoid) std::printf("\n  paranoid: dispatched and undispatched paths agree on every atom\n");
  return (nbad || nvalbad) ? 1 : 0;
}

static void bench(const char* path) {
  std::vector<Mol> mols = load(path);
  long long nat = 0;
  for (const Mol& m : mols) nat += m.n;
  size_t maxn = 0;
  for (const Mol& m : mols) maxn = std::max(maxn, (size_t)m.n);
  std::vector<double> lp(maxn + 1), mr(maxn + 1);

  std::vector<double> reps;
  double sink = 0;
  for (int rep = 0; rep < 11; ++rep) {
    auto t0 = std::chrono::steady_clock::now();
    for (const Mol& m : mols) {
      contribs(m, lp.data(), mr.data());
      // consume EVERY atom, not just atom 0: -O3 can inline contribs() and dead-code the atoms
      // whose results are never read, which would time a fraction of the molecule.
      for (int i = 0; i < m.n; ++i) sink += lp[i] + mr[i];
    }
    auto t1 = std::chrono::steady_clock::now();
    reps.push_back(std::chrono::duration<double, std::micro>(t1 - t0).count() / (double)mols.size());
  }
  std::sort(reps.begin(), reps.end());
  double med = reps[reps.size() / 2];
  std::printf("\ncrippen.cpp typer, %zu molecules, mean %.1f heavy atoms, 11 reps\n",
              mols.size(), (double)nat / (double)mols.size());
  std::printf("  median %.3f us/mol   min %.3f   max %.3f   (spread %+.1f%% / %+.1f%%)\n",
              med, reps.front(), reps.back(),
              100.0 * (reps.front() - med) / med, 100.0 * (reps.back() - med) / med);
  std::printf("  %.4f us per atom\n", med / ((double)nat / (double)mols.size()));
  if (sink == 12345.6789) std::printf("");   // keep the loop alive
}

int main(int argc, char** argv) {
  selfCheck();
  buildDispatch();
  const char* cmd = argc > 1 ? argv[1] : "verify";
  const char* path = argc > 2 ? argv[2] : "cpp/crip_mols.txt";
  if (!std::strcmp(cmd, "verify"))   return verify(path, false);
  if (!std::strcmp(cmd, "paranoid")) return verify(path, true);
  if (!std::strcmp(cmd, "bench"))    { bench(path); return 0; }
  std::fprintf(stderr, "usage: crippen [verify|paranoid|bench] [crip_mols.txt]\n");
  return 1;
}
