// GENERATED by cpp/verify_frag.py -- do not edit.
//
// The pattern SPECIFICATION for the `rdkit_core` descriptor family: 74 rows of
// FragmentDescriptors.csv plus 6 descriptors whose pattern lives in RDKit's C++ and NOT
// in the SMARTS that rdkit/Chem/Lipinski.py prints beside them.  Each row's counting mode
// and, for the non-CSV rows, the corpus measurement that established the pattern, are
// carried here so that the C++ cannot quietly assume a default.  See cpp/verify_frag.py's
// docstring for why four of the six non-CSV rows are not what the module displays.
//
// PROVENANCE.  `SPEC_SHA256` hashes the (name, SMARTS, mode) triples -- the specification.
// `CSV_SHA256` hashes FragmentDescriptors.csv and is INFORMATIONAL ONLY, exactly as
// cpp/estate_tables.h keeps sha256(AtomTypes.py) separate from sha256(_rawD): a file hash
// moves on a copyright or `# $Id$` edit, so it would cry wolf while masking nothing.
// `cpp/verify_frag.py check` compares SPEC and exits non-zero on drift.
//
//   rdkit  2025.09.2   (pin: 2025.9.2)
//   SPEC_SHA256 = ed422b69eb0a409140bbddaa16d974ff6d326407a975eaa40b73c91adfa6fb08
//   CSV_SHA256  = f491d016a2bbf7cb0c3ca4ab23662c0b0ad4e358b028938433ef3b44253a569c   (informational)

#ifndef HUME_FRAG_TABLES_H
#define HUME_FRAG_TABLES_H

#include <cstdint>

namespace frag_tbl {

constexpr const char SPEC_SHA256[] = "ed422b69eb0a409140bbddaa16d974ff6d326407a975eaa40b73c91adfa6fb08";

// Counting mode.  Every row here is UNIQUE: RDKit takes the count as
//     len(GetSubstructMatches(patt, uniquify=True))
// i.e. the number of distinct ATOM SETS, not the number of embeddings.  Measured on 4,000
// molecules of cpp/hard.smi: for all 74 patterns the uniquify=True count equals the number
// of distinct sorted match tuples, so uniquification is well-posed (it cannot depend on
// which embedding RDKit found first).  Measured too: the largest raw (uniquify=False) match
// count over every pattern and every molecule is 180, so RDKit's maxMatches=1000 default
// NEVER truncates on this corpus -- had it truncated, the count WOULD have been order-
// dependent, because truncation happens BEFORE uniquification.
enum CountMode : uint8_t { CM_UNIQUE = 0 };

struct Row {
  const char* name;
  const char* smarts;
  uint8_t     mode;
  uint8_t     n_query_atoms;   // atoms in the TOP-LEVEL query graph
  uint8_t     cyclic;          // 1 if the top-level query graph contains a ring closure
  uint8_t     max_rec_depth;   // 0 == no recursive SMARTS at all
  uint16_t    n_recursive;     // total $(...) sub-queries, all depths
};

constexpr int N_ROWS = 74;
constexpr Row ROWS[N_ROWS] = {
  { "fr_C_O", "[CX3]=[OX1]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_C_O_noCOO", "[C!$(C-[OH])]=O", CM_UNIQUE, 2, 0, 1, 1 },
  { "fr_Al_OH", "[C!$(C=O)]-[OH]", CM_UNIQUE, 2, 0, 1, 1 },
  { "fr_Ar_OH", "c[OH1]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_methoxy", "[OX2](-[#6])-[CH3]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_oxime", "[CX3]=[NX2]-[OX2]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_ester", "[#6][CX3](=O)[OX2H0][#6]", CM_UNIQUE, 5, 0, 0, 0 },
  { "fr_Al_COO", "C-C(=O)[O;H1,-]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_Ar_COO", "c-C(=O)[O;H1,-]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_COO2", "[CX3](=O)[OX1H0-,OX2H1]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_ketone", "[#6][CX3](=O)[#6]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_ether", "[OD2]([#6])[#6]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_phenol", "[OX2H]-c1ccccc1", CM_UNIQUE, 7, 1, 0, 0 },
  { "fr_aldehyde", "[CX3H1](=O)[#6]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_quatN", "[$([NX4+]),$([NX4]=*)]", CM_UNIQUE, 1, 0, 1, 2 },
  { "fr_NH2", "[NH2,nH2]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_NH1", "[NH1,nH1]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_NH0", "[NH0,nH0]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_Ar_N", "n", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_aniline", "c-[NX3;!$(N=*)]", CM_UNIQUE, 2, 0, 1, 1 },
  { "fr_Imine", "[Nv3](=C)-[#6]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_nitrile", "[NX1]#[CX2]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_hdrzine", "[NX3]-[NX3]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_hdrzone", "C=N-[NX3]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_N_O", "[N!$(N=O)](-O)-C", CM_UNIQUE, 3, 0, 1, 1 },
  { "fr_nitro", "[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]", CM_UNIQUE, 2, 0, 1, 2 },
  { "fr_azide", "[$(*-[NX2-]-[NX2+]#[NX1]),$(*-[NX2]=[NX2+]=[NX1-])]", CM_UNIQUE, 1, 0, 1, 2 },
  { "fr_priamide", "C(=O)-[NH2]", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_amidine", "C(=N)(-N)-[!#7]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_guanido", "C(=N)(N)N", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_Nhpyrrole", "[nH]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_imide", "N(-C(=O))-C=O", CM_UNIQUE, 5, 0, 0, 0 },
  { "fr_halogen", "[#9,#17,#35,#53]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_alkyl_halide", "[CX4]-[Cl,Br,I,F]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_sulfide", "[SX2](-[#6])-C", CM_UNIQUE, 3, 0, 0, 0 },
  { "fr_SH", "[SH]", CM_UNIQUE, 1, 0, 0, 0 },
  { "fr_C_S", "C=[SX1]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_sulfone", "S(=,-[OX1;+0,-1])(=,-[OX1;+0,-1])(-[#6])-[#6]", CM_UNIQUE, 5, 0, 0, 0 },
  { "fr_sulfonamd", "N-S(=,-[OX1;+0,-1])(=,-[OX1;+0,-1])-[#6]", CM_UNIQUE, 5, 0, 0, 0 },
  { "fr_urea", "C(=O)(-N)-N", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_term_acetylene", "C#[CH]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_imidazole", "n1cncc1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_furan", "o1cccc1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_thiophene", "s1cccc1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_thiazole", "c1scnc1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_oxazole", "c1ocnc1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_pyridine", "n1ccccc1", CM_UNIQUE, 6, 1, 0, 0 },
  { "fr_piperdine", "N1CCCCC1", CM_UNIQUE, 6, 1, 0, 0 },
  { "fr_piperzine", "N1CCNCC1", CM_UNIQUE, 6, 1, 0, 0 },
  { "fr_morpholine", "O1CCNCC1", CM_UNIQUE, 6, 1, 0, 0 },
  { "fr_lactone", "[C&R1](=O)[O&R1][C&R1]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_tetrazole", "c1nnnn1", CM_UNIQUE, 5, 1, 0, 0 },
  { "fr_epoxide", "O1CC1", CM_UNIQUE, 3, 1, 0, 0 },
  { "fr_unbrch_alkane", "[CR0;D2,D1][CR0;D2][CR0;D2][CR0;D2,D1]", CM_UNIQUE, 4, 0, 0, 0 },
  { "fr_bicyclic", "[R2][R2]", CM_UNIQUE, 2, 0, 0, 0 },
  { "fr_benzene", "c1ccccc1", CM_UNIQUE, 6, 1, 0, 0 },
  { "fr_phos_acid", 
      "[$(P(=[OX1])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),$([OX2]P)])[$([OX2H]),$"
      "([OX1-]),$([OX2]P)]),$([P+]([OX1-])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),"
      "$([OX2]P)])[$([OX2H]),$([OX1-]),$([OX2]P)])]", CM_UNIQUE, 1, 0, 2, 20 },
  { "fr_nitro_arom_nonortho", "[$(c1(-[$([NX3](=O)=O),$([NX3+](=O)[O-])])ccccc1);!$(cc-!:*)]", CM_UNIQUE, 1, 0, 2, 4 },
  { "fr_Al_OH_noTert", "[$(C-[OX2H]);!$([CX3](-[OX2H])=[OX1]);!$([CD4]-[OX2H])]", CM_UNIQUE, 1, 0, 1, 3 },
  { "fr_para_hydroxylation", 
      "[$([cH]1[cH]cc(c[cH]1)~[$([#8,$([#8]~[H,c,C])])]),$([cH]1[cH]cc(c[cH]1)~[$([#7X3,$([#7](~["
      "H,c,C])~[H,c,C])])]),$([cH]1[cH]cc(c[cH]1)-!:[$([NX3H,$(NC(=O)[H,c,C])])])]", CM_UNIQUE, 1, 0, 3, 9 },
  { "fr_allylic_oxid", "[$(C=C-C);!$(C=C-C-[N,O,S]);!$(C=C-C-C-[N,O]);!$(C12=CC(=O)CCC1C3C(C4C(CCC4)CC3)CC2)]", CM_UNIQUE, 1, 0, 1, 4 },
  { "fr_aryl_methyl", "[$(a-[CH3]),$(a-[CH2]-[CH3]),$(a-[CH2]-[CH2]~[!N;!O]);!$(a(:a!:*):a!:*)]", CM_UNIQUE, 1, 0, 1, 4 },
  { "fr_Ndealkylation1", 
      "[$(N(-[CH3])-C-[$(C~O),$(C-a),$(C-N),$(C=C)]),$(N(-[CH2][CH3])-C-[$(C~O),$(C-a),$(C-N),$(C"
      "=C)])]", CM_UNIQUE, 1, 0, 2, 10 },
  { "fr_Ndealkylation2", 
      "[$([N&R1]1(-C)CCC1),$([N&R1]1(-C)CCCC1),$([N&R1]1(-C)CCCCC1),$([N&R1]1(-C)CCCCCC1),$([N&R1"
      "]1(-C)CCCCCCC1)]", CM_UNIQUE, 1, 0, 1, 5 },
  { "fr_alkyl_carbamate", "C[NH1]C(=O)OC", CM_UNIQUE, 6, 0, 0, 0 },
  { "fr_ketone_Topliss", "[$([CX3](=[OX1])(C)([c,C]));!$([CX3](=[OX1])([CH1]=C)[c,C])]", CM_UNIQUE, 1, 0, 1, 2 },
  { "fr_ArN", "[$(a-[NX3H2]),$(a-[NH1][NH2]),$(a-C(=[OX1])[NH1][NH2]),$(a-C(=[NH])[NH2])]", CM_UNIQUE, 1, 0, 1, 4 },
  { "fr_HOCCN", "[$([OX2H1][CX4][CX4H2][NX3&R1]),$([OH1][CX4][CX4H2][NX3][CX4](C)(C)C)]", CM_UNIQUE, 1, 0, 1, 2 },
  { "NumHDonors", "[$([N;!H0;v3]),$([N;!H0;+1;v4]),$([O,S;H1;+0]),$([n;H1;+0])]", CM_UNIQUE, 1, 0, 1, 4 },
  { "NumHAcceptors", 
      "[$([O,S;H1;v2]-[!$(*=[O,N,P,S])]),$([O,S;H0;v2]),$([O,S;-]),$([N;v3;!$(N-*=!@[O,N,P,S])]),"
      "$([nH0,o,s;+0])]", CM_UNIQUE, 1, 0, 2, 7 },
  { "NOCount", "[#7,#8]", CM_UNIQUE, 1, 0, 0, 0 },
  { "NumHeteroatoms", "[!#6;!#1]", CM_UNIQUE, 1, 0, 0, 0 },
  { "NumAmideBonds", "C(=O)N", CM_UNIQUE, 3, 0, 0, 0 },
  { "NumRotatableBonds", 
      "[!$(*#*)&!D1&!$(C(F)(F)F)&!$(C(Cl)(Cl)Cl)&!$(C(Br)(Br)Br)&!$(C([CH3])([CH3])[CH3])&!$([CD3"
      "](=[N,O,S])-!@[#7,O,S!D1])&!$([#7,O,S!D1]-!@[CD3]=[N,O,S])&!$([CD3](=[N+])-!@[#7!D1])&!$(["
      "#7!D1]-!@[CD3]=[N+])]-!@[!$(*#*)&!D1&!$(C(F)(F)F)&!$(C(Cl)(Cl)Cl)&!$(C(Br)(Br)Br)&!$(C([CH"
      "3])([CH3])[CH3])]", CM_UNIQUE, 2, 0, 1, 14 },
};

// NOT a substructure count.  Kept in this file so the table is exhaustive over the
// pattern-shaped members of the family and nobody re-derives it from the SMARTS that
// rdkit/Chem/Lipinski.py displays -- which counts ATOMS where the C++ counts HYDROGENS.
//   NHOHCount = sum(GetTotalNumHs(includeNeighbors=True)) over atoms with Z in {7, 8}
//     evidence: CalcNumLipinskiHBD; 6,000/6,000.  includeNeighbors matters: an explicit [2H] on N is counted, and the atom-counting SMARTS [#8H1,#7H1,#7H2,#7H3] differs on 776/4,000

}  // namespace frag_tbl

#endif
