// GENERATED by cpp/gen_frag_program.py -- do not edit.
//
// The query-program record layout and opcode numbering, shared by every program this
// generator emits (cpp/frag_program.h, cpp/qed_alert_program.h) and by the one evaluator
// that runs them, src/hume_core/frag_matcher.h.
//
// OPCODES ARE APPEND-ONLY.  The number is baked into every generated header; inserting one
// in the middle would silently reinterpret every node of an already-verified program.
//
//   rdkit  2025.09.2   (pin: 2025.9.2)

#ifndef HUME_FRAG_PROG_TYPES_H
#define HUME_FRAG_PROG_TYPES_H

#include <cstdint>

namespace frag_prog_types {

enum Op : uint8_t {
  OP_ATOMAND = 0,
  OP_ATOMOR = 1,
  OP_ATOMNULL = 2,
  OP_ATOMTYPE = 3,
  OP_ATOMATOMICNUM = 4,
  OP_ATOMEXPLICITDEGREE = 5,
  OP_ATOMTOTALDEGREE = 6,
  OP_ATOMHCOUNT = 7,
  OP_ATOMFORMALCHARGE = 8,
  OP_ATOMINNRINGS = 9,
  OP_ATOMTOTALVALENCE = 10,
  OP_ATOMISAROMATIC = 11,
  OP_ATOMISALIPHATIC = 12,
  OP_RECURSIVESTRUCTURE = 13,
  OP_BONDAND = 14,
  OP_BONDOR = 15,
  OP_BONDNULL = 16,
  OP_BONDORDER = 17,
  OP_BONDINRING = 18,
  OP_SINGLEORAROMATICBOND = 19,
  OP_ATOMISOTOPE = 20,
  OP_ATOMINRING = 21,
};
constexpr int N_OPS = 22;

struct Node { uint8_t op; uint8_t neg; int32_t val; int32_t lhs; int32_t rhs; };
struct QBond { int16_t u; int16_t v; int32_t root; };
struct Pattern { const char* label; int32_t a0; int16_t na; int32_t b0; int16_t nb; };
struct Named { const char* name; int32_t pattern; };
struct Spec { const char* name; const char* smarts; };

// A whole compiled program, as one bindable value.  `fragmatch::Matcher` holds a pointer
// to this and to nothing else global, which is what lets one evaluator run both sets.
struct Program {
  const char*    name;
  const char*    spec_sha256;
  const Node*    nodes;
  const int32_t* aroots;
  const QBond*   qbonds;
  const Pattern* patterns;
  int            n_patterns;
  const Named*   named;
  int            n_named;
};

}  // namespace frag_prog_types

#endif
