"""Generate cpp/chiwalk_tables.h -- the three element tables the Chi/WalkCount port needs.

RUN IT IN THE PINNED MORDRED ENV, AND ONLY THERE:

    uv run --isolated --no-project --python 3.11 --with "mordred==1.2.0" \
           --with "rdkit==2025.9.2" --with "numpy==1.26.4" python cpp/gen_chiwalk_tables.py

WHY A GENERATOR RATHER THAN A TRANSCRIPTION. Two of the three tables are not constants in any
file -- they are *derived* by mordred at import time:

  * `vdw_volume = vdw_radii.map(lambda r: 4.0/3.0*np.pi*r**3)`. Retyping the radii and redoing
    the arithmetic in C++ would put a libm `pow` between us and mordred's answer for no gain, so
    the DERIVED volume is emitted here as a %.17g double. The C++ then does no element
    arithmetic at all.
  * `nOuterElecs` is RDKit's periodic table, read through `Chem.GetPeriodicTable()`. It is an
    RDKit datum, not a mordred one, and the drift guard should therefore ask RDKit.

`polarizalibity94.txt` really is a file of constants, but it is emitted the same way so that all
three tables come from the same live process and carry the same version banner.

MISSING ENTRIES ARE NaN AND THAT IS LOAD-BEARING. mordred's `PeriodicTable.load` turns a `-`
cell into `np.nan`, and `AtomicProperty.calculate` then FAILS THE WHOLE DESCRIPTOR if any atom
of the molecule maps to NaN. So `Mv`/`Mp`/`Sp` are NaN -- not "NaN for that atom" -- for a
molecule containing one element with no table row. The C++ reproduces that by propagating NaN
through the sum, which gives the same answer for the same reason.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from rdkit import Chem

from mordred import _atomic_property as ap

HERE = Path(__file__).resolve().parent
OUT = HERE / "chiwalk_tables.h"

ZMAX = 118


def row(vals, per=6):
    out, cur = [], []
    for v in vals:
        cur.append(v)
        if len(cur) == per:
            out.append("    " + ", ".join(cur) + ",")
            cur = []
    if cur:
        out.append("    " + ", ".join(cur) + ",")
    return "\n".join(out)


def dbl(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "NANV"
    return "%.17g" % float(x)


def main() -> None:
    pt = Chem.GetPeriodicTable()
    banner = (f"rdkit {Chem.rdBase.rdkitVersion}  numpy {np.__version__}  "
              f"python {sys.version.split()[0]}")

    nouter = [pt.GetNOuterElecs(z) for z in range(0, ZMAX + 1)]     # index by Z, 0 unused
    pol = [ap.polarizability94[z] for z in range(0, ZMAX + 1)]
    vol = [ap.vdw_volume[z] for z in range(0, ZMAX + 1)]

    # mordred's `AtomicProperty.carbon` is prop(Chem.Atom(6)) -- the value for a bare carbon.
    carbon_p = ap.get_polarizability(Chem.Atom(6))
    carbon_v = ap.get_vdw_volume(Chem.Atom(6))
    carbon_Z = float(ap.get_atomic_number(Chem.Atom(6)))

    txt = f"""// GENERATED by cpp/gen_chiwalk_tables.py -- DO NOT EDIT.
// {banner}
//
// Three element tables for src/hume_core/chi.h and src/hume_core/topomisc.h.
//
//   NOUTER_ELECS[z]  RDKit's GetPeriodicTable().GetNOuterElecs(z); the `Zv` of mordred's
//                    valence-electron count `dv`.
//   POL94[z]         mordred/data/polarizalibity94.txt, NaN where the file says `-`.
//   VDW_VOL[z]       4/3 pi r^3 ALREADY EVALUATED in the pinned process, so the C++ never
//                    calls pow() on a radius and cannot disagree with mordred's libm.
//
// Index by atomic number. Z = 0 is a placeholder; z > ZMAX is NaN by the accessor, matching
// mordred's PeriodicTable.__getitem__ which returns NaN for an out-of-range index rather than
// raising.
#ifndef HUME_CHIWALK_TABLES_H
#define HUME_CHIWALK_TABLES_H

#include <limits>

namespace chiwalk_tables {{

static constexpr int ZMAX = {ZMAX};
#define NANV (std::numeric_limits<double>::quiet_NaN())

static const int NOUTER_ELECS[ZMAX + 1] = {{
{row([str(v) for v in nouter], 12)}
}};

static const double POL94[ZMAX + 1] = {{
{row([dbl(v) for v in pol], 5)}
}};

static const double VDW_VOL[ZMAX + 1] = {{
{row([dbl(v) for v in vol], 5)}
}};

// mordred's AtomicProperty.carbon: the property evaluated on a bare Chem.Atom(6).
static constexpr double CARBON_POL = {dbl(carbon_p)};
static constexpr double CARBON_VDW_VOL = {dbl(carbon_v)};
static constexpr double CARBON_Z = {dbl(carbon_Z)};

#undef NANV

inline double pol94(int z) {{
  if (z < 1 || z > ZMAX) return std::numeric_limits<double>::quiet_NaN();
  return POL94[z];
}}
inline double vdwVol(int z) {{
  if (z < 1 || z > ZMAX) return std::numeric_limits<double>::quiet_NaN();
  return VDW_VOL[z];
}}
inline int nOuterElecs(int z) {{
  if (z < 0 || z > ZMAX) return 0;
  return NOUTER_ELECS[z];
}}

}}  // namespace chiwalk_tables

#endif  // HUME_CHIWALK_TABLES_H
"""
    OUT.write_text(txt)
    nan_pol = [z for z in range(1, ZMAX + 1) if np.isnan(pol[z])]
    nan_vol = [z for z in range(1, ZMAX + 1) if np.isnan(vol[z])]
    print(f"[gen_chiwalk_tables] {banner}")
    print(f"wrote {OUT}  ({len(txt)} bytes)")
    print(f"polarizability94 NaN for Z = {nan_pol}")
    print(f"vdw_volume       NaN for Z = {nan_vol}")
    print(f"carbon: p={carbon_p!r} v={carbon_v!r} Z={carbon_Z!r}")


if __name__ == "__main__":
    main()
