"""Dump Mordred's own element tables into cpp/ac_tables.h. Generator, not a transcription.

    uv run --with mordred==1.2.0 --with rdkit python cpp/gen_ac_tables.py

The six table-lookup autocorrelation weights (i, p, v, se, pe, are) are per-element constants
that used to be fetched one Python call per atom, at 473.9 us/mol for the nine vectors. They are
constants, so they belong in a header -- but a RETYPED table is a new way to be subtly wrong, and
this project has already lost four rounds each to a hand-copied HallKierAlpha table and a
hand-guessed BCUT2D convention. So the header is GENERATED: this script imports the installed
mordred and reads `_atomic_property`'s already-parsed `PeriodicTable.data` lists, which is the
same object the getters index. Re-run it after any mordred bump and the diff is visible.

WHAT IS AND IS NOT A TABLE (mordred/_atomic_property.py, v1.2.0):

    i    ionization_potentials[Z]        NOT "intrinsic state" -- that getter is short `s`
    p    polarizability94[Z]
    v    4/3 pi vdw_radii[Z]^3
    se   sanderson[Z]                    pe  pauling[Z]      are  allred_rocow[Z]
    d    # of non-hydrogen neighbours                        (bonding, no table)
    dv   (Zv - h) / (Z - Zv - 1)                             (bonding + NOuterElecs)
    c    Gasteiger, stays in RDKit

MISSING ELEMENTS ARE NaN, NOT AN ERROR. `PeriodicTable.__getitem__` returns NaN for Z < 1 and
for Z past the end of the file, and the loader maps a "-" cell to NaN. Every table therefore
runs to Z=118 here, padded with NaN, so the C++ lookup is a plain bounds-free index and reproduces
mordred's NaN exactly rather than reading off the end of a shorter array.

NOuterElecs comes from RDKit's periodic table, not mordred's, because that is where `dv` gets it.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

ZMAX = 118
HERE = Path(__file__).resolve().parent


def emit(name: str, data: list[float], comment: str, zero: str = "NAN") -> str:
    """One C++ array, Z-indexed with a real slot 0 so ELEM[Z] needs no -1.

    Slot 0 is reached by RDKit dummy atoms (`*`, atomic number 0). mordred's PeriodicTable
    returns NaN there, so a dummy atom kills the six table weights but NOT c, d or dv --
    and RDKit's GetNOuterElecs(0) is 0, so AC_NOUTER's slot 0 is 0.0, not NaN.
    """
    vals = [zero]
    for z in range(1, ZMAX + 1):
        v = data[z - 1] if z - 1 < len(data) else float("nan")
        vals.append("NAN" if not np.isfinite(v) else f"{v!r}")
    body = ""
    for i in range(0, len(vals), 6):
        body += "    " + ", ".join(vals[i:i + 6]) + ",\n"
    return f"// {comment}\nstatic const double {name}[{ZMAX + 1}] = {{\n{body}}};\n\n"


def main() -> None:
    import mordred
    from mordred import _atomic_property as ap
    from rdkit import Chem, rdBase

    pt = Chem.GetPeriodicTable()
    nouter = [float(pt.GetNOuterElecs(z)) for z in range(1, ZMAX + 1)]

    tables = [
        ("AC_IP", ap.ionization_potentials.data, "i   ionization potential  [data/ionization_potential.txt]"),  # noqa: E501
        ("AC_POL", ap.polarizability94.data, "p   polarizability (1994)  [data/polarizalibity94.txt]"),
        ("AC_VDWVOL", ap.vdw_volume.data, "v   vdW volume = 4/3 pi r^3  [data/van_der_waals_radii.txt]"),
        ("AC_SE", ap.sanderson.data, "se  Sanderson EN  [data/sanderson_electron_negativity.txt]"),
        ("AC_PE", ap.pauling.data, "pe  Pauling EN  [data/pauling_electron_negativity.txt]"),
        ("AC_ARE", ap.allred_rocow.data, "are Allred-Rochow EN  [data/allred_rocow_electron_negativity.txt]"),
    ]
    tables = [(n, d, c, "NAN") for n, d, c in tables] + [
        ("AC_NOUTER", nouter,
         "outer-shell electron count, from RDKit's periodic table (used by dv)", "0.0"),
    ]

    head = (f"// GENERATED by cpp/gen_ac_tables.py -- DO NOT EDIT BY HAND.\n"
            f"// Source: mordred {mordred.__version__} `_atomic_property` tables, "
            f"RDKit {rdBase.rdkitVersion} periodic table.\n"
            f"// NAN means the element is absent from mordred's table; mordred marks the whole\n"
            f"// weight vector missing in that case, and so does ac.cpp.\n"
            f"#pragma once\n#include <cmath>\n\n")
    out = head + "".join(emit(n, d, c, z) for n, d, c, z in tables)
    (HERE / "ac_tables.h").write_text(out)

    have = {n: sum(1 for z in range(1, ZMAX + 1)
                   if z - 1 < len(d) and np.isfinite(d[z - 1])) for n, d, _, _ in tables}
    print(f"wrote {HERE / 'ac_tables.h'} | mordred {mordred.__version__} | "
          f"defined elements: " + ", ".join(f"{k.split('_')[1]}={v}" for k, v in have.items()))


if __name__ == "__main__":
    main()
