"""What is LEFT of the autocorrelation block that is not cpp/ac.cpp.

    uv run --with rdkit --with numpy python cpp/time_ac_rdkit.py

The nine weight vectors moved into C++ (cpp/ac_weights.h, tables generated by
cpp/gen_ac_tables.py), so the only chemistry the block still asks RDKit for is AddHs and the
Gasteiger charge. Both are C++ routines called ONCE PER MOLECULE, which is the same situation
cpp/time_rdkit_cpp.py already argues is a legitimate C++ measurement: one Python->C++ boundary
crossing plus the C++ work, with the boundary measured against a trivial accessor and SUBTRACTED.
That is an upper bound on a native caller, which pays no boundary at all.

This is emphatically NOT the measurement `ap.getters` was. Mordred evaluated the weights in
Python, nine calls per ATOM, so its 473.9 us/mol was an interpreter measurement -- overhead being
removed, never a result.

Runs on the same H-ADDED graph the block uses (mols_h.smi), because AddHs roughly triples the
atom count and Gasteiger is per-atom.
"""
from __future__ import annotations

import time
from pathlib import Path

import numpy as np
from rdkit import Chem, RDLogger
from rdkit.Chem import rdPartialCharges

RDLogger.DisableLog("rdApp.*")
HERE = Path(__file__).resolve().parent
REPS = 5


def bench(mols, fn, label, baseline=0.0):
    bad = 0
    try:
        fn(mols[0])
    except Exception:
        pass
    ts = []
    for r in range(REPS):
        t0 = time.perf_counter()
        for m in mols:
            try:
                fn(m)
            except Exception:
                if r == 0:
                    bad += 1
        ts.append(time.perf_counter() - t0)
    return max(min(ts) / len(mols) * 1e6 - baseline, 0.0), label, bad


def main() -> None:
    smis = HERE.joinpath("mols_h.smi").read_text().split()
    heavy = [m for m in (Chem.MolFromSmiles(s) for s in smis) if m is not None]
    mols = [Chem.AddHs(m) for m in heavy]
    na = float(np.mean([m.GetNumAtoms() for m in mols]))
    print(f"{len(mols):,} molecules, mean {na:.1f} atoms WITH H, {REPS} reps, best-of\n")

    over, _, _ = bench(mols, lambda m: m.GetNumAtoms(), "overhead")
    print(f"  per-call Python->C++ boundary: {over:.3f} us  (subtracted below)\n")

    rows = [bench(heavy, Chem.AddHs, "AddHs (the H-added graph itself)", over),
            bench(mols, rdPartialCharges.ComputeGasteigerCharges,
                  "Gasteiger charges (PEOE, 12 iters)", over)]
    print(f"  {'step':44s} {'us/mol':>9s} {'failed':>8s}")
    for us, label, bad in rows:
        print(f"  {label:44s} {us:9.2f} {bad:8d}")
    print(f"  {'-' * 54}\n  {'RDKit C++ still in the block':44s} "
          f"{sum(u for u, _, _ in rows):9.2f}")


if __name__ == "__main__":
    main()
