// GENERATED by cpp/gen_vsa_tables.py -- do not edit.
//
// The numeric specification of the VSA-binning descriptor family: Labute ASA's covalent
// radii and bond-shortening constants, and the five arrays of bin edges that SlogP_VSA,
// SMR_VSA, PEOE_VSA, EState_VSA and VSA_EState bucket their per-atom property with.
//
// PROVENANCE.  `spec` is sha256 over the IEEE-754 bit patterns of every number below, in
// the canonical rendering cpp/gen_vsa_tables.py:canonical() defines and
// src/hume_core/vsa_bins.h:spec_string() reproduces.  vsa_bins.h RECOMPUTES it at load
// and throws if it disagrees, so editing a bin edge here is caught in C++ with no RDKit
// in the process.  The two `file` hashes are INFORMATIONAL: they move when a comment or a
// copyright year moves, which is exactly the false alarm the spec hash exists to avoid.
//
// Regenerate under THE PIN.  An unpinned `--with rdkit` silently becomes a different
// oracle and the exactness check cannot see it, because both sides move together:
//     uv run --isolated --python 3.12 --with "rdkit==2025.9.2" --with "numpy==2.4.6" \
//            python cpp/gen_vsa_tables.py
//
//   rdkit   2025.09.2   (pin: 2025.9.2)
//   numpy   2.4.6
//   python  3.12.13
//   spec    sha256(numbers) = 47217aab0d1b7b93c53fb275820c16b8c3e8adb5ba8fe35fd2815e9d2c6b4d6b
//   file    sha256(EState_VSA.py) = fdaf63990d2e9d833657a07f7fca6ed80d5d4e8d765e60bccd84632d838f48a2   (informational)
//   file    sha256(MolSurf.py) = 614b65501d75de8e371cec9244493a68aca83554a5a987076f254f7e76d6e8af   (informational)

#ifndef HUME_VSA_TABLES_H
#define HUME_VSA_TABLES_H

namespace vsa_tbl {

constexpr char SPEC_SHA256[] = "47217aab0d1b7b93c53fb275820c16b8c3e8adb5ba8fe35fd2815e9d2c6b4d6b";

// PeriodicTable::getRb0(z).  Index is the atomic number; index 0 and everything past Cm
// is 0.0, which is what RDKit's own table holds -- an element with no Rb0 gets a sphere
// of radius zero and contributes nothing, rather than being an error.
constexpr int MAX_Z = 118;
constexpr double RB0[MAX_Z + 1] = {
    0.0, 0.33, 0.7, 1.23, 0.9, 0.82, 0.77, 0.7,
    0.66, 0.611, 0.7, 1.54, 1.36, 1.18, 0.937, 0.89,
    1.04, 0.997, 1.74, 2.03, 1.74, 1.44, 1.32, 1.22,
    1.18, 1.17, 1.17, 1.16, 1.15, 1.17, 1.25, 1.26,
    1.188, 1.2, 1.17, 1.167, 1.91, 2.16, 1.91, 1.62,
    1.45, 1.34, 1.3, 1.27, 1.25, 1.25, 1.28, 1.34,
    1.48, 1.44, 1.385, 1.4, 1.378, 1.387, 1.98, 2.35,
    1.98, 1.69, 1.83, 1.82, 1.81, 1.8, 1.8, 1.99,
    1.79, 1.76, 1.75, 1.74, 1.73, 1.72, 1.94, 1.72,
    1.44, 1.34, 1.3, 1.28, 1.26, 1.27, 1.3, 1.34,
    1.49, 1.48, 1.48, 1.45, 1.46, 1.45, 2.4, 2.0,
    1.9, 1.88, 1.79, 1.61, 1.58, 1.55, 1.53, 1.07,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
};

// PeriodicTable::getNOuterElecs(z).  rdkit/Chem/EState/EState.py:EStateIndices computes
// dv = GetNOuterElecs(Z) - GetTotalNumHs(); this is that table, read out of RDKit rather
// than transcribed from a periodic chart.
constexpr int NOUTER[MAX_Z + 1] = {
    0, 1, 2, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5,
    6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 2, 3,
    4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
    2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 3, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15, 4, 5, 6, 7, 8, 9, 10, 11,
    2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 3, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2,
};

// getLabuteAtomContribs(): `const double bondScaleFacts[4] = {.1, 0, .2, .3};`, indexed
// by Bond::BondType.  0 UNSPECIFIED, 1 SINGLE, 2 DOUBLE, 3 TRIPLE.  An aromatic-FLAGGED
// bond uses index 0 whatever its type; a type >= 4 with the flag clear shortens by 0.
constexpr double BOND_SCALE[4] = {0.1, 0.0, 0.2, 0.3};

// MolSurf.cpp calcSlogP_VSA / MolSurf.py logpBins
constexpr int N_LOGP_BINS = 11;
constexpr double LOGP_BINS[N_LOGP_BINS] = {-0.4, -0.2, 0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6};

// MolSurf.cpp calcSMR_VSA / MolSurf.py mrBins
constexpr int N_MR_BINS = 9;
constexpr double MR_BINS[N_MR_BINS] = {1.29, 1.82, 2.24, 2.45, 2.75, 3.05, 3.63, 3.8, 4.0};

// MolSurf.cpp calcPEOE_VSA / MolSurf.py chgBins
constexpr int N_CHG_BINS = 13;
constexpr double CHG_BINS[N_CHG_BINS] = {-0.3, -0.25, -0.2, -0.15, -0.1, -0.05, 0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3};

// EState_VSA.py estateBins (no C++ equivalent)
constexpr int N_ESTATE_BINS = 10;
constexpr double ESTATE_BINS[N_ESTATE_BINS] = {-0.39, 0.29, 0.717, 1.165, 1.54, 1.807, 2.05, 4.69, 9.17, 15.0};

// EState_VSA.py vsaBins (no C++ equivalent)
constexpr int N_VSA_BINS = 9;
constexpr double VSA_BINS[N_VSA_BINS] = {4.78, 5.0, 5.41, 5.74, 6.0, 6.07, 6.45, 7.0, 11.0};

}  // namespace vsa_tbl

#endif  // HUME_VSA_TABLES_H
