// GENERATED by cpp/verify_ic.py -- do not edit.
//
// rdkit 2025.09.2 | numpy 2.4.6 | spec sha256[:16] = b6709757430f3b5b
//
// The spec hash is over the three VECTORS, not over any RDKit file: PORT_STATUS.md house rule 6
// -- a file hash cries wolf on a copyright edit and stays silent on a table that moved.
#ifndef HUME_IC_TABLES_H
#define HUME_IC_TABLES_H
namespace ic_tbl {

constexpr int Z_MAX = 118;

// PeriodicTable::getAtomicWeight(z). Class weight for ModifiedIC (repair R3).
constexpr double ATOMIC_WEIGHT[Z_MAX + 1] = {
    0.0, 1.008, 4.003, 6.941, 9.012, 10.812, 12.011, 14.007, 15.999, 18.998, 20.18, 22.99,
    24.305, 26.982, 28.086, 30.974, 32.067, 35.453, 39.948, 39.098, 40.078, 44.956, 47.867,
    50.944, 51.996, 54.938, 55.845, 58.933, 58.693, 63.546, 65.39, 69.723, 72.61, 74.922, 78.96,
    79.904, 83.8, 85.468, 87.62, 88.906, 91.224, 92.906, 95.94, 98.0, 101.07, 102.906, 106.42,
    107.868, 112.412, 114.818, 118.711, 121.76, 127.6, 126.904, 131.29, 132.905, 137.328,
    138.906, 140.116, 140.908, 144.24, 145.0, 150.36, 151.964, 157.25, 158.925, 162.5, 164.93,
    167.26, 168.934, 173.04, 174.967, 178.49, 180.948, 183.84, 186.207, 190.23, 192.217,
    195.078, 196.967, 200.59, 204.383, 207.2, 208.98, 209.0, 210.0, 222.0, 223.0, 226.0, 227.0,
    232.038, 231.036, 238.029, 237.0, 244.0, 243.0, 247.0, 247.0, 251.0, 252.0, 257.0, 258.0,
    259.0, 262.0, 267.0, 268.0, 269.0, 270.0, 269.0, 278.0, 281.0, 281.0, 285.0, 284.0, 289.0,
    288.0, 293.0, 292.0, 294.0,
};

// PeriodicTable::getDefaultValence(z); -1 means "no single default", and such an atom is never
// a kekulization candidate.
constexpr int DEFAULT_VALENCE[Z_MAX + 1] = {
    -1, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, 3, 4, 3, 2, 1, 0, 1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, 2, 3, 2, 1,
    0, 1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, 2, 3, 2, 1, 0, 1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
};

// PeriodicTable::getNOuterElecs(z). >= 5 is "has a lone pair to spend", which is the branch that
// decides whether a formal charge raises or lowers the valence an aromatic atom is aiming at.
constexpr int N_OUTER_ELECS[Z_MAX + 1] = {
    0, 1, 2, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
    2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 3,
    4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 4, 5, 6, 7, 8, 9, 10, 11, 2, 3, 4, 5, 6, 7, 8, 1,
    2, 3, 4, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2,
};

}  // namespace ic_tbl
#endif  // HUME_IC_TABLES_H
