"""The 178 verified block columns, in the order the C++ emits them.

GENERATED, NOT TYPED, and the distinction is the point. The order is defined in exactly one
place -- `blocks_row()` in src/hume_core/hume_blocks.h -- and these names were emitted from the
same module NAMES lists that cpp/verify_hume.py builds its SPEC from, so the package cannot
disagree with the harness about which number is which. Regenerate rather than edit:

    python -c "import chi, cycles, conjugation, stereo, resistance; ..."   # see git history

ONE PAIR SHARES A NAME AND IS NOT THE SAME DESCRIPTOR: BalabanJ and BalabanJ_mordred. Same
formula, weighted against unweighted distance matrix -- 2.888052 against 1.925368 on
naphthalene. Both are verified against RDKit; the second reproduces mordred's argument choice.
"""
from __future__ import annotations

COLUMNS: tuple[str, ...] = (
    # BalabanJ / BalabanJ_mordred -- same formula, weighted vs unweighted distance matrix
    "BalabanJ",
    "BalabanJ_mordred",
    # chi.py
    "chi0n",
    "chi1n",
    "chi2n",
    "chi3n",
    "chi4n",
    "chi5n",
    "chi6n",
    "chi7n",
    "chi0v",
    "chi1v",
    "chi2v",
    "chi3v",
    "chi4v",
    "chi5v",
    "chi6v",
    "chi7v",
    "path1",
    "path2",
    "path3",
    "path4",
    "path5",
    "path6",
    "path7",
    "path_total",
    "path_ratio",
    "chi_nv_ratio",
    # cycles.py, minus C_sssr and C_redundancy (see cpp/verify_hume.py)
    "C3",
    "C4",
    "C5",
    "C6",
    "C7",
    "C8",
    "C_total",
    "C_maxlen",
    "C_minlen",
    "pa3_max",
    "pa4_max",
    "pa5_max",
    "pa6_max",
    "pa7_max",
    "pa8_max",
    "pa3_mean",
    "pa4_mean",
    "pa5_mean",
    "pa6_mean",
    "pa7_mean",
    "pa8_mean",
    "pa_all_max",
    "pa_all_mean",
    "pa_all_std",
    "frac_in_cycle",
    "n_multi_cycle",
    "C5_het",
    "C6_het",
    "C5_arom",
    "C6_arom",
    "C6_carbo",
    # conjugation.py
    "n_sys",
    "conj_atoms",
    "conj_frac",
    "sys_max",
    "sys_max_frac",
    "sys_2nd",
    "sys_mean",
    "sysbin0",
    "sysbin1",
    "sysbin2",
    "sysbin3",
    "sysbin4",
    "sysbin5",
    "diam_max",
    "linearity",
    "diam_sum",
    "branch_pts",
    "branch_frac",
    "extra_arom",
    "extra_arom_frac",
    "extra_arom_max",
    "het_in_max",
    "het_frac_max",
    "sys_max_rings",
    # stereo.py
    "S_sum",
    "S_absum",
    "S_sum_norm",
    "S_central",
    "S_mass",
    "SATS1",
    "SATS2",
    "SATS3",
    "SATS4",
    "SATS5",
    "SATS6",
    "SATS_far",
    "T_sum",
    "T_absum",
    "n_EZ_any",
    "TATS1",
    "TATS2",
    "TATS3",
    "TATS4",
    "XATS1",
    "XATS2",
    "XATS3",
    "XATS4",
    # resistance.py
    "RATSC0_m",
    "RATSC0_e",
    "RATSC0_p",
    "RATSC0_v",
    "RPAIR0",
    "RATSC1_m",
    "RATSC1_e",
    "RATSC1_p",
    "RATSC1_v",
    "RPAIR1",
    "RATSC2_m",
    "RATSC2_e",
    "RATSC2_p",
    "RATSC2_v",
    "RPAIR2",
    "RATSC3_m",
    "RATSC3_e",
    "RATSC3_p",
    "RATSC3_v",
    "RPAIR3",
    "RATSC4_m",
    "RATSC4_e",
    "RATSC4_p",
    "RATSC4_v",
    "RPAIR4",
    "Kf",
    "Kf_n",
    "Kf_norm",
    "Cyclicity",
    "Cyclicity_n",
    "DeltaMax",
    "DeltaMean",
    "RW2_mean",
    "RW2_std",
    "RW2_max",
    "RW2_q90",
    "RW3_mean",
    "RW3_std",
    "RW3_max",
    "RW3_q90",
    "RW4_mean",
    "RW4_std",
    "RW4_max",
    "RW4_q90",
    "RW6_mean",
    "RW6_std",
    "RW6_max",
    "RW6_q90",
    "RW8_mean",
    "RW8_std",
    "RW8_max",
    "RW8_q90",
    "RW12_mean",
    "RW12_std",
    "RW12_max",
    "RW12_q90",
    "RW16_mean",
    "RW16_std",
    "RW16_max",
    "RW16_q90",
    # RDKit tail: Kappa1-3, HallKierAlpha, BCUT2D x8.
    # The four E-state extremes that used to head this tail are gone: vsa_bins.h emits them, from
    # the copy of the index built in RDKit's own association order, and having both made four
    # column names appear twice in ALL_COLUMNS.
    "Kappa1",
    "Kappa2",
    "Kappa3",
    "HallKierAlpha",
    "BCUT2D_MWHI",
    "BCUT2D_MWLOW",
    "BCUT2D_CHGHI",
    "BCUT2D_CHGLO",
    "BCUT2D_LOGPHI",
    "BCUT2D_LOGPLOW",
    "BCUT2D_MRHI",
    "BCUT2D_MRLOW",
)

N_COLS = len(COLUMNS)
# 178, not 182: the four E-state extremes moved to the RDKit block (vsa_bins.h), which
# already emitted them. See the note in the RDKit tail above.
assert N_COLS == 178, N_COLS
